### ISSUE TITLE
Can not download

### ISSUE THREAD

**Issue by Planetical** [processhacker/processhacker#1028]
When I attempt to download using the exe, I get this error message.
![Screenshot_397](https://user-images.githubusercontent.com/53327121/140623153-1ab2fd3a-ff02-46da-b062-2e184b3f0cff.png)
I have attempted to find ways to fix on my own, but it is not working. This is what shows up in the event viewer.
![Screenshot_398](https://user-images.githubusercontent.com/53327121/140623178-b178e6a9-9be2-4603-9c79-fdd1ace2dd42.png)
Running as administrator does not help.

**Comment by dmex** [comment]
I checked the binary and it downloads and installs without issue. Either your download was interrupted or the binary was corrupted after it was downloaded (by either malware or antivirus).

The file hashes are on the website. You can check the hash by opening powershell and executing 
`Get-FileHash -Algorithm SHA256 "path-to-file-here"`

It should equal:
`2592EC9B98E6B079F49EDCBF9201AF44D19C22F40C2495A32AED807D62D6DAF0`

**Comment by Planetical** [comment]
My hash does equal this, but it still won't open.

**Comment by Planetical** [comment]
It also says that windows cannot access the specified device, path, or file and that i may not have the appropriate permissions to access the item. I have no clue how to fix that

**Comment by Masamune3210** [comment]
Sounds like defender is pulling its normal to me, it tends to cause weird errors if its scanning or quarantining a file

**Comment by Planetical** [comment]
I have defender turned off, and any other anti-virus is off as well. I'm not sure why it's doing it.

**Comment by Masamune3210** [comment]
Defender re-enables itself after a set time unless you do some heavy edits to stop it from doing so, so its prob worth checking either  way

**Comment by dmex** [comment]
> I have defender turned off, and any other anti-virus is off as well. I'm not sure why it's doing it.

You would switch to an AV that isn't garbage. My best recommendation is malwarebytes because they don't bullshit customers and have the best support: https://www.malwarebytes.com/

> It also says that windows cannot access the specified device, path, or file and that i may not have the appropriate permissions to access the item. I have no clue how to fix that

That `cannot access the specified device` error and the other `side by side configuration` error in your event log are both either caused by corrupted downloads or something tampering/modifying the binary after download - either way the executable isn't valid and Windows will throw either of those errors and some others.

Why the binary is getting corrupted could either be malware/spyware or something else. You would have to figure out what's causing it.
