### ISSUE TITLE
AV prevents me from getting setup

### ISSUE THREAD

**Issue by Thehappycoder123** [processhacker/processhacker#1036]
My antivirus (trend micro) flags this as spyware and so im wondering if 1. Is it safe to use and 2. Will it clash with my AV in any way

**Comment by microdee** [comment]
It's safe to use, the code is open and under the scrutiny of all public eye. It provides utilities which is really hard to live without if you're in IT. Anti-viruses flag this because of its name, its kernel level access and because it is not endorsed by a high stonks TrustyCorp™ Inc. I bet it's also flagged because the unexperienced user can do some real harm with it to their own system, but you have to be really clumsy to do so. It might be also not favored by anti-cheat stuff because it has some tools which can bootstrap some surface-level reverse engineering effort, youknow, it shows all the information that is available about a process.
