### ISSUE TITLE
Menu View, item "Hide signed processes"

### ISSUE THREAD

**Issue by Speravir** [processhacker/processhacker#1048]
The item “Hide signed processes” in menu _View_ should only be displayed if the necessary setting in _Options > General_ is enabled instead of displaying an ~~error~~ message (OK it’s an informational message).

Or if this setting is disabled, but someone clicks on the menu item, a clear warning should be shown that this setting will be changed if going further and after another click this setting should be enabled automatically.

I would prefer the first variant.

**Comment by dmex** [comment]
> The item “Hide signed processes” in menu View should only be displayed if the necessary setting in Options > General is enabled instead of displaying an error message (OK it’s an informational message).

The reason it was done this way is because if it doesn't show any messages and instead greyed out, nobody would know why the menu was disabled and also won't know how to enable it.

Letting you select the menu and showing the message informing you why it didn't work was the better option? 

> after another click this setting should be enabled automatically.

The dialog should probably ask to enable the setting now rather than making you do go find it?

**Comment by Speravir** [comment]
> Letting you select the menu and showing the message informing you why it didn't work and what needs to happen is better?

Yes, you are right.

> The dialog should probably ask to enable the setting now rather than making you do go find it?

The message as it is now is much better! So, let me close this issue ticket.
