### ISSUE TITLE
cache path

### ISSUE THREAD

**Issue by NightRaidGamer** [processhacker/processhacker#1056]
Hi, I would like to know how do I change the cache path to any other place? I mean "AppData \ Roaming \ Process Hacker"

**Comment by Biswa96** [comment]
Are you using the portable version? The ZIP file from here https://processhacker.sourceforge.io/nightly.php

**Comment by NightRaidGamer** [comment]
> Are you using the portable version? The ZIP file from here https://processhacker.sourceforge.io/nightly.php

no, i'm using the master version

**Comment by dmex** [comment]
> how do I change the cache path to any other place?

The portable version uses the current directory (wherever that is when executing the portable) otherwise it can't be customized just yet... The temp directory can't be used because that location is banned by antivirus, so it uses the 'cache' directory and always automatically deletes the cache after the build is installed.

**Comment by NightRaidGamer** [comment]
@Biswa96 @dandv thanks
