### ISSUE TITLE
Strange discrepancies in performance data

### ISSUE THREAD

**Issue by Bartolomeus-649** [processhacker/processhacker#1061]
Performance values from different places in the application seem to have larger discrepancies than what can be expected.

Not really sure if this is a bug/problem or not, perhaps the metrics show different things, but I can't find any info on what each of these metrics relay show.

![image](https://user-images.githubusercontent.com/7513795/146503309-9fef6662-287f-448e-878a-c2a558833009.png)

The cliped-in capture of Windows Task manager is not from the exact same time as the other graphs, but the magnitude of the values  and their relation to what's shown in the main screenshot are in proportion.

**Comment by dmex** [comment]
> Performance values from different places in the application seem to have larger discrepancies than what can be expected.

Those disk statistics are retrieved from ETW and are completely different to the eprocess I/O statistics hence the 'large deprecancies' because they're not the same and can't be compared. The Disk I/O statistics shown on that same page are where you'll see the etw disk statistics matching those graphs. 

If you're trying to compare the values with task manager then use the link that task manager page for opening resource monitor which is what uses these ETW statistics.
