### ISSUE TITLE
Adding a command which will gently close the selected process

### ISSUE THREAD

**Issue by unforgettableid** [processhacker/processhacker#108]
Process Hacker already includes a "Terminate" command, but no "Close gently" command.

It would be good if you could please add this "Close gently" command, as the very first item on the process context menu.  Then you could rename the existing "Terminate" command to "Terminate forcibly".

The "Close gently" command could gracefully close the selected process by sending WM_CLOSE to its main window.  Source:  http://stackoverflow.com/questions/2055753/how-to-gracefully-terminate-a-process

P.S.  Thank you very much for writing and maintaining Process Hacker!

**Comment by ferenczy** [comment]
I think this used to be implemented, it was called _Terminator_ as far as I remember. Basically, it was trying various methods to end a process, from the most "gentle" (like sending the `WM_CLOSE` message) to the most aggressive (like corrupting process' memory).

I don't know why it has been removed, I have used it rather then classic terminate.

**Comment by dmex** [comment]
@ferenczy 

The Terminator was removed from official builds due to Avast claiming it was malware and Valve Corporation claiming it was 'cheat software' and banning users who terminated games. 

You can still use it but you need to compile it manually from the other repository: https://github.com/processhacker2/plugins-extra/tree/master/TerminatorPlugin

**Comment by ferenczy** [comment]
Thank you for the explanation @dmex. 

Couldn't you release also builds of those extra plugins, please? Or at least share what I need to build it? I didn't find any readme or instructions there.

BTW Terminator contains the option to terminate a process "gently", am I right?

**Comment by dmex** [comment]
> Terminator contains the option to terminate a process "gently", am I right?

Yep.

> Or at least share what I need to build it? I didn't find any readme or instructions there.

You can find some instructions here:
https://wj32.org/processhacker/forums/viewtopic.php?t=2801#p9194

After setting up the repository and opening the plugins-extra.sln solution; You can right-click the Terminator project inside Visual Studio and select Rebuild to compile the plugin.

Let me know if you have any problems 👍

**Comment by diversenok** [comment]
Btw, some time ago there was an ability to install additional pre-compiled plugins directly from PH plugins menu. Why this feature was disabled? I think it would be nice if extra-plugins will be available without installing VS and compiling them.

Of course, some plugins (like Terminator) shouldn't be installed by default, but what about a simple possibility to install any of them without installing several gigabytes of Visual Studio?

**Comment by dmex** [comment]
@ diversenok 

> there was an ability to install additional pre-compiled plugins directly from PH plugins menu. Why this feature was disabled?

This was implemented as a separate plugin. I merged the 'stable' parts of that code into the main program but HTTP support within the base program is non-existent. It'll be re-added once the http code is stable: https://github.com/processhacker2/processhacker/blob/master/plugins/CommonUtil/http.c#L22

> what about a simple possibility to install any of them without installing several gigabytes of Visual Studio?

You only need to install the "Build Tools for Visual Studio 2017" (170mb) and run \build\build_release.cmd

**Comment by dmex** [comment]
@gvanem 

Wininet has delay-loaded imports which call LoadLibrary at runtime. Your stacktrace would look something like this:
myapp.exe -> LoadLibrary("my_lib.dll") ->DllMain -> InternetOpenUrlA -> LoadLibrary("ws2_32.dll")

LoadLibrary can't be called during DllMain since DllMain is already inside the earlier LoadLibrary and you need to static-link against wininet, load the dlls before loading your dll or call wininet functions from outside DllMain (e.g. new thread). 

Most of the DllMain restrictions are listed here under 'general best practices':
https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-best-practices

**Comment by gvanem** [comment]
@dmex Thanks for the hints. I'll try these.
