### ISSUE TITLE
About WindowExplorer plugin and x86 processes

### ISSUE THREAD

**Issue by UCyborg** [processhacker/processhacker#130]
When running x64 version of Process Hacker, certain details about the windows of x86 applications are missing, eg. the address of window procedure. If I understand correctly, this is due to limitation of Windows API and you're employing a trick involving DLL injection in a process of interest to get this information in its context.

While I don't know if there's a trick that could be used to display this information in the x64 version, which would certainly come in handy sometimes, given that the x86 version of Process Hacker is bundled along with the x64 version (installer version), maybe the WindowExplorer plugin could be added to it for completeness sake. It does seem to work.

**Comment by timofonic** [comment]
@dmex Any hopes to get it fixed? I did think to be a failure of my system...

**Comment by dmex** [comment]
>  you're employing a trick involving DLL injection in a process of interest to get this information

The injection was removed entirely a few years ago when Google Chrome was silently uninstalling Process Hacker via it's built-in "Chrome Cleanup Tool".

I'm closing this ticket since this feature won't be coming back. The procedure address won't be available for now using the pervious implementation.
