### ISSUE TITLE
Tree state not restored after search

### ISSUE THREAD

**Issue by pszalanski** [processhacker/processhacker#186]
I have a bunch of subtrees that I collapse on each start, like `winit.exe` or `chrome.exe`, which launches one process per browser tab.

If I search a process and clear the search, the "collapsed state" of my processes is not restored. I have to reapply collapsing all trees that don't matter to me.

Could you implement storing that state between searches?

**Comment by dmex** [comment]
If you use the Process menu > Miscellaneous > "Collapse by default option" then the collapsed state is restored after clearing the search?

**Comment by pszalanski** [comment]
No way! I absolutely did not know that option. That works! Thanks!

But I still think that the collapsed state should be stored across searches.

**Comment by dmex** [comment]
>  I still think that the collapsed state should be stored across searches.

I've tried restoring the node states after searches by creating lists of existing processes/nodes/states... The caches/hashlists for nodes are reused when new nodes are added/removed and the state doesn't get restored properly.

The "Collapse by default" option also has a sperate database which needs to be synchronized so the only way this would work is if we disable updating the processes list when there is an active search so that things can be restored properly later. "Collapse by default" is based on the image not the individual process/nodes which is why it works in this case but doesn't work for individual process/nodes.
