### ISSUE TITLE
Process Hacker spawns deadlocked processes?

### ISSUE THREAD

**Issue by TETYYS** [processhacker/processhacker#204]
I noticed Process Hacker spawns processes where one of them is deadlocked
![processhacker_2017-12-15_20-48-32](https://user-images.githubusercontent.com/3091645/34055786-6aaea678-e1d9-11e7-8a1b-9fb53ac9b58a.png)

PH 3.0.1123

**Comment by dmex** [comment]
>3.0.1123

latest version is 1128

**Comment by dmex** [comment]
@TETYYS 

> Process Hacker spawns processes

It'll spawn a process when you try preform an action that requires elevation. What were you doing when this happened?

**Comment by TETYYS** [comment]
Nope, I don't think so

**Comment by TETYYS** [comment]
I updated to 1145 and the problem still occurs

One process spawns each time I try to look at any 32-bit process thread stack trace, but doesn't spawn more than 2 processes. Second process always deadlocks. It spawns the x86 version of ProcessHacker (in x86 folder I have beside with 64-bit ProcessHacker.exe), I now even get this (pic) every time I try to look at thread stack trace. Spawned processes are created with -phsvc parameter

![processhacker_2017-12-17_02-08-19](https://user-images.githubusercontent.com/3091645/34075419-2c6229de-e2cf-11e7-9106-1d04c62aa9d6.png)

**Comment by dmex** [comment]
> I now even get this (pic) every time I try to look at thread stack trace

Right-click the file and untick this option:
https://i.imgur.com/wIwcpvn.png

> spawns each time I try to look at any 32-bit process thread stack trace

Process Hacker spawns the x86 version when querying .NET process stack traces. Were you inspecting a .NET process or something else?

BTW none of this code has changed since 2015 and the x86 version doesn't deadlock on my machine so I have no idea why its crashing on your machine unless either your security software in doing something dodgy or your .NET framework installation is corrupted.

**Comment by TETYYS** [comment]
More information - this happens when querying a .NET process run as SYSTEM. Clicking cancel on x86 'Security Warning' still successfully displays the stack trace

**Comment by dmex** [comment]
Fixed 👍
