### ISSUE TITLE
Include date compiled or commit hash in Help > About

### ISSUE THREAD

**Issue by Baddest-Juju** [processhacker/processhacker#217]
I want to make sure I consistently compile plugins-extra with the version of Process Hacker I am using. For this reason I ask that you include the date of compilation of the new version or the commit hash.

**Comment by Baddest-Juju** [comment]
Just realized that info is in https://wj32.org/processhacker/nightly.php

It would still be convenient but it's not worth having an open issue.

**Comment by stdedos** [comment]
I'd include _a way, in general, to match changelogs with build numbers_

Since nightly builds are more or less incremental fixes, someone may not want to go the extra mile "for a minor fix" every day

**Comment by dmex** [comment]
> match changelogs with build numbers

I'm going to include the commit hash in the binary image. The changelog window can then query the commit history directly from the Github API and show newer/older entries depending on the branch (stable/nightly) with richer details about the changes: https://api.github.com/repositories/50824485/commits

> Since nightly builds are more or less incremental fixes, someone may not want to go the extra mile "for a minor fix" every day

The 'nightly' branch is not exactly every night. 😄 

The updater only checks for updates once every 7 days displaying 1 update prompt and if you cancel the prompt it won't do anything again for another 7 days. The nightly builds are also compiled by Appveyor which are currently triggered manually to ensure it'll only compile commits that are actually somewhat stable instead of simply the latest commit (since some commits might be incomplete or untested).

**Comment by stdedos** [comment]
@dmex Is this change merged now?

**Comment by dmex** [comment]
@stdedos 

The about window includes the SHA hash 👍

**Comment by stdedos** [comment]
@dmex Hoo-ray 😺

**Comment by dmex** [comment]
@stdedos 

Malicious software might abuse the hashes and I'm not sure if it'll be a permanent feature just yet... I guess we'll see how it goes over the next few months.
