### ISSUE TITLE
Feature request: Kill processes and make them stay dead

### ISSUE THREAD

**Issue by elfchief** [processhacker/processhacker#239]
It would be wonderful if Process Hacker had a feature similar to the save-and-restore-process-priority feature, which instead was a 'kill this process and keep it killed'.

This would be really useful for those obnoxious processes that just refuse to stay dead (I'm looking at YOU, OfficeClickToRun.exe). Seems like it could be a similar interface, "permanently kill this process", "permanently kill this command line", along with a short blacklist of processes that can't be killed this way (explorer, process hacker, etc)

(Best I can tell there's not really a tool out there that can do this, short of just running a scheduled "kill task named X" job or something, which just feels ... dirty. Process Hacker already knows everything that's running and presumably has an efficient way to keep that list updated, so adding something like this seems like it would be pretty easy.)

**Comment by diversenok** [comment]
I can offer you to try [my program](https://github.com/diversenok/ExecutionMaster/#execution-master) in this case (I'm also planning to make a plugin for PH with the same functionality soon).

Among other things, @dmex frequently references [ObCallback driver](https://github.com/Microsoft/Windows-driver-samples/tree/master/general/obcallback) that can be very useful here since it can deny process execution. What about using PsSetCreateProcessNotifyRoutineEx in KProcessHacker?

**Comment by Mattiwatti** [comment]
Another method that often works surprisingly well given how simple it is:
- Right click executable and go to file permissions -> 'advanced' -> 'change permissions'.
- Click 'add...' -> 'advanced' -> 'find now' and select the 'Everyone' RDN. OK twice.
- Check the 'traverse folder / execute file' checkbox in the **Deny** column. (Rest can stay empty.)
- Click OK and ignore the Windows warning about setting a deny permission since that was the whole point. OK your way out.

This method has permanently killed many random Visual Studio exes, telemetry crapware files and even drivers on my system. It is of course trivial to undo this (unlike a kernel mode ObRegisterCallbacks driver), but no one ever seems to check for file permissions for some reason.

**Comment by tigros** [comment]
what's worked for me for several years now is autohotkey.

most importantly to shut the avira free nagging popup.

a script for avira would go something like this:

    #NoTrayIcon
    #persistent
    settimer, check, 1000
    return

    check:
    process, exist, ipmgui.exe
    if errorlevel
    {
        sleep, 1000
        process, close, ipmgui.exe
    }
    return

the sleep is just because sometimes u could get error popup depending on timing, not required for all progs.

Mattiwatti's idea seemed like a good one but get error popup when avira tries to bug me.
