### ISSUE TITLE
feature request: duration to show terminated processes

### ISSUE THREAD

**Issue by Zekfad** [processhacker/processhacker#272]
Can you make configuration for display duration of killed processes.
And ability to manual delete "terminated" rows if duration is infinity.

**Comment by dmex** [comment]
> Can you make configuration for display duration of killed processes.

Have you tried increasing the Options > Highlighting > 'Highlighting duration' value from 1000 (1 second) to 10000 (10 seconds)? 😉

> And ability to manual delete "terminated" rows if duration is infinity.

I don't think this would be possible since 'rows' and the process information are stored in memory and machine resources are limited. If you forget to delete 'terminated rows' then after a few hours/days you'll run out of available system memory.

If you need to keep terminated records you could log the information to disk using the Options > Notifications - Logging and review the file for terminated processes?
