### ISSUE TITLE
New feature: show desktop program process as first on process tree

### ISSUE THREAD

**Issue by piotrex** [processhacker/processhacker#282]
New feature idea: option to show Windows taskbar processes / tray processes (explorer.exe childs or sth) as first on process tree like System explorer does:
![aa](https://i.imgur.com/7ZPRiIW.png)

**Comment by VictorVG** [comment]
This idea seems to me unsuccessful - the sense of the process tree in showing the real hierarchy of processes in the OS, and SE shows a distorted picture in which the virtual desktop point Desktop is chosen as the reference point, which guarantees errors in the OS control commands, since it will lead to the indication of the wrong process paths.

**Comment by ygoe** [comment]
What's the process tree sorted by after all, on one level? It's not the name and not the PID. What else is it then? Random? explorer.exe is mostly near the end of its tree level but doesn't have the highest ID.

**Comment by VictorVG** [comment]
Just clik Process tab, Name field,

**Comment by ygoe** [comment]
No idea what you're trying to tell me, sorry.
