### ISSUE TITLE
Killing Zombies process (Files handle)

### ISSUE THREAD

**Issue by Geolim4** [processhacker/processhacker#303]
I noticed that is some cases, PH cannot kill completely a process because this process has some active file handle.

Going to the zombie process and removing unclosed handles generally solve it and terminate the process definitely.

I was wondering if you could add a check after killing a process like "If it's still not dying prompt the user and ask him if we wanna try to detach all the unclosed file handle".

**Comment by dmex** [comment]
> try to detach all the unclosed file handle

https://blogs.technet.microsoft.com/markrussinovich/2005/08/17/unkillable-processes/

**Comment by dmex** [comment]
> I think you misunderstood what I'm trying to say. 

This feature has been included with the Terminator plugin (CH1 option) since 2009 😃
https://i.imgur.com/aNYgxJS.png

> I'm aware that an unkillable process is generally caused by a file/stream handle that stays stuck.

'unkillable' processes are caused by faulty 3rd party kernel drivers. A user-mode process can never prevent its termination from kernel-mode (and become 'unkillable') unless something else running in kernel-mode does something to prevent it.

> I'm going to its handles (right clic-> properties) and I'm manually closing all file handles.

If you uninstall or update the driver on the machine causing the problem then you won't need to use other termination methods 😉
