### ISSUE TITLE
KProcesshacker verify.c bug

### ISSUE THREAD

**Issue by hzqst** [processhacker/processhacker#308]
verify.c
```cpp
NTSTATUS KpiVerifyClient(
    _In_ PVOID CodeAddress,
    _In_reads_bytes_(SignatureSize) PUCHAR Signature,
    _In_ ULONG SignatureSize,
    _In_ PKPH_CLIENT Client
    ){
//......
    KphVerifyClient(Client, CodeAddress, Signature, SignatureSize);
//.....
```

`KphVerifyClient(Client, CodeAddress, Signature, SignatureSize);`
should be
`KphVerifyClient(Client, CodeAddress, signature, SignatureSize);`

**Comment by dmex** [comment]
Good catch! Thank you for reporting this! 👍 

I've been playing with the code and it doesn't seem to be exploitable or impact client verification in any way which is very lucky and I'm following this up with some researchers to see if they might be able to do something with it.

Kinda funny too. Over the last 6 months we've had conversations with Avast, Kaspersky and Sophos who reviewed this very code and they didn't spot that bug 😄

If you're able to exploit this or introduce a crash/blue screen then please let us know since any driver crashes/blue screen issues are a CVE that require public disclosure.

Thanks again for reporting this!
