### ISSUE TITLE
DPI Awareness does not update

### ISSUE THREAD

**Issue by poizan42** [processhacker/processhacker#313]
Changes to DPI awareness are not reflected by the DPI awareness column, you have to restart PH to see it.

**Comment by dmex** [comment]
This is intentional because processes are prevented from changing their DPI after creating a window and also don't change their DPI awareness more than once after startup.

Can you give me an example of a program that changes the DPI more than once causing Process Hacker to show the wrong value? 

------

Continuation of https://github.com/processhacker/processhacker/pull/312#discussion_r217430919

> I'm not sure if I follow you. Do you want PHPN_DPIAWARENESS to be removed completely? I wasn't sure if it was being used somewhere else.

No. Process Hacker invalides cached column data by removing the flag after each interval update here:
https://github.com/processhacker/processhacker/blob/master/ProcessHacker/proctree.c#L647

**Comment by poizan42** [comment]
@dmex Just try making a blank wpf application in Visual Studio without adding any manifest. Half of the times you start it PH will list it as DPI unaware because it queried the value before WPF got to setting it.
