### ISSUE TITLE
GPU load not working in Windows 10 Ver 2.39

### ISSUE THREAD

**Issue by IRainman** [processhacker/processhacker#381]
Ver 2.39.124
![default](https://user-images.githubusercontent.com/3396559/53194204-dd88dc00-3623-11e9-92b7-3dd20f8dcceb.PNG)

**Comment by dmex** [comment]
Does Process Explorer show any GPU usage?
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by IRainman** [comment]
No, it also shows zero loading for all 32 nodes.
![2](https://user-images.githubusercontent.com/3396559/53263112-81888b00-36e9-11e9-9d47-6924e37b6fd1.PNG)

**Comment by dmex** [comment]
I had this same issue on my dev machine after upgrading from 1803 to 1809 last year... Your nvidia driver is not getting initialized correctly during startup and is using software rasterization mode. 

Task Manager uses performance counters for querying GPU information while Process Explorer/Process Hacker query GPU information directly from the dxgi kernel interface. If your gpu adapter is using software rasterization mode then you won't see any GPU information in Process Explorer/Process Hacker because graphics are being handled by software instead of the hardware.

1) Download the latest version: https://www.nvidia.com/Download/index.aspx
2) Uninstall the current driver.
3) Reboot.
4) Install the latest version.
5) Reboot.

You might have to do this a few times before the nvidia setup properly resets the driver configuration.

**Comment by Apocalypse612** [comment]
I am having this same exact issue right now. I'm on Win 10 x64 Version 1803 (OS Build 17134.590).

My GPU is being read correctly by the standard Windows Task Manager, but it's not on Process hacker. I have the latest nightly build. It's reporting 0% usage during all benchmarks. 

I have the latest NVidia driver, too. Please help. 

NVIDIA GeForce GTX 1080 Ti

**Comment by dmex** [comment]
@Apocalypse612 

You need to reset the driver using the above instructions.

**Comment by Apocalypse612** [comment]
@dmex 

I have followed your instructions precisely, and it's still not getting GPU reporting accurately. It's still at 0%. However, during benchmarks the ram amount used does increase... It just doesn't display in the graph. 

Did you use any tools like display driver uninstaller while uninstalling your drivers?

**Comment by dmex** [comment]
@Apocalypse612 

I didn't use any uninstaller tools but it did take a few attempts. You could also try using the nightly builds which include a bunch of fixes for GPU usage:
https://wj32.org/processhacker/nightly.php

**Comment by Apocalypse612** [comment]
Yep, I'm on the latest nightly and latest 1080ti driver version. No go.

**Comment by dmex** [comment]
You could try the Display Driver Uninstaller (DDU) from wagnardsoft:
https://www.wagnardsoft.com/DDU/download/DDU%20v18.0.0.9.exe
https://www.guru3d.com/files-details/display-driver-uninstaller-download.html

I'm not really sure how to fix the nvidia driver  issue other than resetting the driver or reinstalling Windows. It did take a few uninstall/reinstall attempts before the driver stopped using software rasterization which fixes querying the node utilization from kernel mode.

**Comment by Apocalypse612** [comment]
@dmex I tried it again this morning. Booted to safe mode, uninstalled with DDU, rebooted, reinstalled a stripped-down version of my NVIDIA GTX driver package (without the bloatware) using the "NVIDIA driver slimming utility". Still nothing. Did it twice, even. 

It would be a lot of work and effort to reinstall my OS since I've made so many changes and have so many apps, and my guess would be that it still wouldn't work. So, I'm at a loss. Is there any other way we can force the GPU out of software rasterisation mode? Or perhaps, use a different means to check that that's actually happening?

Best Regards

**Comment by dmex** [comment]
I'm closing this since it's a 3rd party issue.

> use a different means to check that that's actually happening?

It also affects Process Explorer from Microsoft so there isn't much anyone can do it... Nvidia need to fix the bug in their software.

**Comment by ileathan** [comment]
Have this issue with 3 different pcs running 3 different GPU generations :(

Has anyone got it working?

**Comment by sercatp** [comment]
> Have this issue with 3 different pcs running 3 different GPU generations :(

That seems to be NVidia drivers bug:
https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-telsaonwindows-no425.25controlpanel

But the solution they propose doesn't work for me. Still no GPU usage and no GPU memory stats too in Process Explorer.
