### ISSUE TITLE
Which Process Hacker web site URL to recommend to others?

### ISSUE THREAD

**Issue by JasonFossen** [processhacker/processhacker#383]
Thanks for maintaining Process Hacker, it's such a great app!

There are several Process Hacker-related web sites.  Which URL would you prefer be used whenever promoting or discussing Process Hacker with others?  

- https://github.com/processhacker
- https://wj32.org/processhacker/
- https://sourceforge.net/projects/processhacker/
- https://processhacker.sourceforge.io

Or a different URL?
Thanks!

**Comment by dmex** [comment]
The official URLs is https://github.com/processhacker

The other links depend on the situation and preference. The large majority of universities/hotels/businesses block the github/sourceforge domains so you would need to use wj32.org in those instances while a large majority of recent malware/spyware/rootkit developers end up targeting the v2.39 release from sourceforge because they don't know we're now using github 😄
