### ISSUE TITLE
Trend Micro Potentially unwanted application?

### ISSUE THREAD

**Issue by taylorh140** [processhacker/processhacker#408]
Well I really like Process Hacker. However Trend Micro seems to think its a "unwanted application"

> Well I want Process Hacker.

https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/PUA.Win32.ProcHack.A

It seems like it has been the trend lately to demonize PH.

**Comment by dmex** [comment]
> arrives on a system as a file dropped by other malware or as a file downloaded unknowingly by users when visiting malicious sites. http://processhacker.{BLOCKED}forge.net/

What malware or websites are 'dropping' Process Hacker? It's interesting they consider Sourceforge malicious.

> Before doing any scans, Windows 7, Windows 8, Windows 8.1, and Windows 10 users must disable System Restore to allow full scanning of their computers.

System restore can block TrendMicro...... so you should disable it?  🤔

> It seems like it has been the trend lately to demonize PH.

It does a lot more damage to their brand and product since its showing the incompetence of these companies and employees more than anything. These pages have so many errors and lack any references and information that you would get a failing grade at school.

They might mislead some unsuspecting customers into thinking their 'security' products are protecting them from some type of threat but they don't mislead security experts and software developers who are using Process Hacker or have reviewed our source-code.

If they were able to show malicious usage of Process Hacker then we could do something about it but not even one company has been able to produce anything to the development team or anywhere else.

**Comment by RossWang** [comment]
> arrives on a system as a file dropped by other malware or as a file downloaded unknowingly by users when visiting malicious sites

Oh, I think I know what happened.
They found Process Hacker when they checked their customers' compromised computers.
Some hackers(script kiddie) use Process Hacker as their tool.

Years ago, my friend had a computer exposing remote desktop in the wild and got hacked. I checked his computer and found the hacker mining Bitcoin and see the portable version of Process Hacker stored in the hacker's working directory.

So Trend Micro thought they need to clean up this file.

But I don't think this is a good way to do this.

**Comment by dmex** [comment]
> So Trend Micro thought they need to clean up this file. But I don't think this is a good way to do this.

They've classified the project (and by extension the owner and developer) as Malware/Spyware on their "Threat Encyclopedia" and state this multiple times on those webpages and in their desktop UI shown to users.

> my friend had a computer exposing remote desktop in the wild and got hacked. They found Process Hacker when they checked their customers' compromised computers.

If that was true then why are they claiming the project is malware/spyware and how was Process Hacker able to compomise RDP?

How are we supposed to fix whatever security issue when these companies don't contact the development team?

**Comment by RossWang** [comment]
They only claim the project is PUA.
> arrives on a system as a file dropped by other malware or as a file downloaded unknowingly by users when visiting malicious sites

Process Hacker was not going to be used to compromise RDP. I think the hacker use Process Hacker for the following two purposes.

1. Terminate or suspend antivirus service
2. Check if the miner process is running properly (They create a script to determinate if the built-in task manager is running, once it finds the task manager is running, the miner was terminated immediately to prevent the user finding anything abnormal. So they need another tool to check if the miner is running normally.)

I think Trend Micro should detect and roll back the change the hacker made instead of create a signature to detect Process Hacker as PUA.

--------------------------------

Here are some screenshots
![2-1](https://user-images.githubusercontent.com/13231557/56483207-07af2b00-64fb-11e9-8f3d-478c675c14f0.png)

I found Process Hacker running in another account they created.
The interesting thing is that the first letter is different.
![1-1](https://user-images.githubusercontent.com/13231557/56482838-c4ec5380-64f8-11e9-92f2-915d4668ab65.png)

**Comment by zzColin** [comment]
It seems that some notable ransomware attacks utilized Process Hacker.

**Comment by dmex** [comment]
> They only claim the project is PUA.

The classification is Malware in their 'threat' directory and they terminate/remove PH using the same dialogs and messages for actual malware.

> It seems that some notable ransomware attacks utilized Process Hacker.

How exactly did they utilize Process Hacker? 

These vendors are not sharing information with the development team so how are we supposed to fix security issues?

**Comment by kleuter** [comment]
It's crazy but there're numerous of another "security" apps that treat PH as unwanted/risky/hacking tool:
- DrWeb
- Kaspersky
- Yandex
- Sophos AV
- [many others](https://www.virustotal.com/#/file/28042dd4a92a0033b8f1d419b9e989c5b8e32d1d2d881f5c8251d58ce35b9063/detection)

**Comment by bitraid** [comment]
I've seen malware in the past using PH to terminate AVs and do their "stuff" while the service is restarted (`ProcessHacker.exe -c -ctype process -cobject ekrn.exe -caction terminate -s`).  It seems that AV companies think that if PH ends up in the systems of their customers, it's most likely through a malware and want to play it safe by marking the tool as a treat (instead of the script that's using it). The same problem has Nir Sofer with his password recovery tools (http://nirsoft.net/). They might as well classify Powershell as PUA because alot of malware use it to compromise systems.

**Comment by dmex** [comment]
> I've seen malware in the past using PH to terminate AVs

You need physical access to the machine with administrative level access? You could just as easily install windbg or livekd and modify the live kernel during runtime but Trend Micro doesn't block actual kernel debuggers? So why are they targeting Process Hacker that doesn't have those same privileges?

You could even execute this powershell script and render the entire machine and operating system permanently unusable and Trend Micro doesn't even block this: https://gist.github.com/dmex/5885ec528b8231fb75d5a591845b96e6

Trend Micro also hasn't reported any security issues to the development team so I think their classification of Process Hacker is clearly unwarranted and likely aimed at targeting open-source applications capable of detecting and removing malware/rootkits their products are unable to detect.

**Comment by bitraid** [comment]
I totally agree that the trend (pun intended) of security companies to mark legitimate programs as threats is totally unjustified.
