### ISSUE TITLE
ETW rundown for registry events

### ISSUE THREAD

**Issue by rabbitstack** [processhacker/processhacker#418]
I'm aware PH has an ETW-based [plugin](https://processhacker.sourceforge.io/doc/etwmon_8c_source.html) to collect disk/net I/O events from NT Kernel Logger ETW provider. It also relies on rundown provider to enumerate all open file objects for the purpose of deriving the file name from file object reference. Do you know if rundown provider is able to log open registry keys or system handles?

Thanks

**Comment by dmex** [comment]
> able to log open registry keys

Event 24 of the Registry class has rundown events for open registry keys.
https://docs.microsoft.com/en-us/windows/desktop/etw/registry

> or system handles
https://docs.microsoft.com/en-us/windows/desktop/etw/obhandlerundownevent

> PH has an ETW-based plugin to collect disk/net I/O events

It's not configured for these events and even then handle/registry events are practically useless because they don't include some types of accesses. If you compare the ETW events to Process Monitor you will see the etw events are missing entries.
