### ISSUE TITLE
Registry and Secure System fake processes have no parent

### ISSUE THREAD

**Issue by andrew-boyarshin** [processhacker/processhacker#425]
For quite some time on 20H1 `Registry` and `Secure System` processes have no parent in process tree. In properties, they are correctly shown as being children to PID 4, but instead of `System (4)` it is `Non-existent process (4)`. `smss.exe` and `Memory Compression` do not exhibit the issue.

**Comment by Biswa96** [comment]
The behavior is same as Process Explorer. Those are minimal process where PEB and TEB are absent. So it may be correct.

**Comment by andrew-boyarshin** [comment]
@Biswa96 I'm aware of that (and I checked Process Explorer too). But some time ago (probably on 19H1) these processes were correctly displayed as children of System process. Plus, there is an ambiguous situation with `Non-existent process (4)` instead of `System (4)` (of course PID 4 exists, but it is not resolved correctly).

**Comment by Biswa96** [comment]
Hmm.. Seems interesting. One test can be done. Take same ProcessHacker version (nightly) in both Windows 10 versions and compare results. If different then there are some cool things added in 20H1 :nerd_face:

**Comment by andrew-boyarshin** [comment]
@Biswa96 18362, latest Process Hacker nightly:
![yep](https://user-images.githubusercontent.com/3063662/59144126-1dba7180-89fd-11e9-8959-e44e939692e2.png)

**Comment by dmex** [comment]
@Biswa96 

> The behavior is same as Process Explorer. Those are minimal process where PEB and TEB are absent. So it may be correct.

No.

@andrew-boyarshin 

> Registry and Secure System processes have no parent in process tree. In properties, they are correctly shown as being children to PID 4, but instead of System (4) it is Non-existent process (4)

> Plus, there is an ambiguous situation with Non-existent process (4) instead of System (4) (of course PID 4 exists, but it is not resolved correctly).

Process IDs are re-cycled on Windows and you can't simply assign the parent process to that value because it will show the wrong parent process. Process Explorer and Process Hacker validate the CreationTime of the ParentProcessId is less than the CreationTime of the child process before assigning the parent (because the parent process can't possibly be created after child processes).

The problem on Windows 10 and the Registry and Secure System processes is that they have creation times before the System process creation time while also specifying System as the parent process.

It's a stupid bug which should have been fixed years ago. The parent process should never be created after the child process which is why Process Explorer and Process Hacker show the wrong parent:

![image](https://user-images.githubusercontent.com/1306177/59152577-086a3500-8a47-11e9-8422-ac59d227e6bc.png)

However, I added a workaround for Process Hacker by using a new Windows 10 feature introduced on RS4 called ProcessSequenceNumber which is a guaranteed monotonic function for every process. Process Explorer does not use this new feature which is why its parenting is still broken on Windows 10 but Process Hacker does make use of the ProcessSequenceNumber instead of the CreationTime of the ParentProcessId which is highly reliable since its guaranteed monotonic:

![image](https://user-images.githubusercontent.com/1306177/59152606-e6bd7d80-8a47-11e9-9868-5072e8b42a54.png)

The problem here is that querying the ProcessSequenceNumber is only supported on RS4 and above and Process Hacker needs to know the exact build number before using this feature otherwise it'll use the wrong offsets and blue screen the machine.

I can't add build numbers for insider because they're too volatile. Some builds add broken features while other builds modify, fix or revert those same changes and issues before changing them again later... It's just a massive waste of time trying to support insider builds until they're stable.

If you want Process Hacker to use ProcessSequenceNumber and dozerns of other new Win10 features (that would otherwise be dissabled on the insider builds) then you need to add the insider build number here: https://github.com/processhacker/processhacker/blob/master/phlib/global.c#L210-L215

**Comment by andrew-boyarshin** [comment]
@dmex Thanks for the explanation (I did know about process ID recycling, but the rest was new to me). Although I don't understand why not use `PROCESSINFOCLASS` 92 for this particular purpose. It should not BSoD the OS in case wrong parameters (like not implemented information class) and do the job. Did `PROCESSINFOCLASS` ever change (except appending new values)? Why rely on `SYSTEM_PROCESS_INFORMATION_EXTENSION` that looks so fragile?

**Comment by dmex** [comment]
>  I don't understand why not use PROCESSINFOCLASS 92 for this particular purpose.

Process Hacker builds a hashlist of processes for adding/removing from the processes tree before it's possible to open a handle to the process and query that information class making it difficult to implement easily.

>  It should not BSoD the OS in case wrong parameters (like unimplemented information class) nor cause access violation and should do the job.

The version number for Process Hacker is global for both the user and kernel which is also used for configuring the driver offsets and that's why it can BSOD the machine.

> Why rely on SYSTEM_PROCESS_INFORMATION_EXTENSION that looks so fragile?

The code is extremely efficient and works good (when the version is known). I didn't want to completely change wj32's code more than necessary in that instance because it's the best possible implementation at present.

> P.S. There's also UINT64 PsGetProcessSequenceNumber(EPROCESS*), but obviously that requires having EPROCESS and seems less stable.

That's extremely unreliable.

**Comment by TETYYS** [comment]
> > P.S. There's also UINT64 PsGetProcessSequenceNumber(EPROCESS*), but obviously that requires having EPROCESS and seems less stable.

> That's extremely unreliable.

How come? Shouldn't kernel functions be reliable?

**Comment by andrew-boyarshin** [comment]
@TETYYS documented —  yes, their API is stable. But `PsGetProcessSequenceNumber` is only exported, not in any documentation. So there is no guarantee that there will be no changes to it (addition/removal/change of input argument type, removal from exports etc.). If PH takes dependency on such undocumented API, any changes to it will certainly cause PH crash at _best_, more likely BSoD.
