### ISSUE TITLE
Option to enable linux-like CPU usage display

### ISSUE THREAD

**Issue by TETYYS** [processhacker/processhacker#429]
It would be pretty cool to have an option to make Process Hacker display process CPU usage non-relative to CPU core count (so full 1 core CPU usage would be equal 100% process CPU usage)

**Comment by Hanif1601** [comment]
How it works or give any screenshot for this idea?

**Comment by TETYYS** [comment]
You can see this kind of CPU usage display in `htop` on linux

**Comment by Bartolomeus-649** [comment]
Is this thread related in any way?

Like, one process with one thread uses 25% of all available CPU time on a machine with 4 cores.
 - What value would this display if the thread run one and the same core all the time?
 - What value would be displaced if the OS schedule this single thread on multiple cores?


If a single thread uses 30% of all available CPU time on a machine with 4 cores.
 - What value would be displayed if the OS schedule this thread on one core to 80% and another one to 40%? Would it display 80%, 40%, 120% (relative to one core) or perhaps 60% (average core usage) or something else?

**Which "problem" is this way of displaying CPU utilization supposed to solve?**

**Comment by dmex** [comment]
> Which "problem" is this way of displaying CPU utilization supposed to solve?

It doesn't solve anything and introduces more problems.

Linux processes are single-threaded and when you create new 'threads' you're in fact creating a new process (sharing the same address space as the other processes) -  thread affinity is fixed to a single core and never schedules to other cores.

Windows processes are multi-threaded and when you create new 'threads' they're re-using the existing process (since threads don't share address space with other processes on Windows) - thread affinity is dynamic and schedules to any available free cores.

http://www.informit.com/articles/article.aspx?p=370047&seqNum=3

> To the Linux kernel, there is no concept of a thread. Linux implements all threads as standard processes. The Linux kernel does not provide any special scheduling semantics or data structures to represent threads. Instead, a thread is merely a process that shares certain resources with other processes. Each thread has a unique task_struct and appears to the kernel as a normal process (which just happens to share resources, such as an address space, with other processes).
>
> This approach to threads contrasts greatly with operating systems such as Microsoft Windows...

A Linux process can never utilize more than 25% of the processor because its single-threaded and it makes sense for Linux to show 100% utilization when that process (thread) has 25% utilization of a single core (of a 4 core machine) because that's the absolute maximum the thread (process) can ever utilize.

A Windows process can utilize more than 25% of the processor because its multi-threaded and it does not make sense for Windows to show 100% utilization when that process (thread) has 25% utilization of a single core (of a 4 core machine) because its not actually utilizing the available processor/scheduling capabilities on Windows. 

This is the TLDR version of Linux vs Windows process/thread/scheduling internals and (glossing over a great many details) an its why there are no Windows tools that show utilization the same way Linux does and vice-versa why there are no Linux tools showing utilization the same way Windows does.

I could add the capability into Process Hacker to show utilization the same way Linux does but it would not be in any way an accurate representation of the actual utilization. You would also be introducing various issues that would obscure bugs and other development problems because of the inaccurate reporting. 

Even if the percentage could be made accurate; ffmpeg shows 600% utilization of the processor on two different machines and almost everyone would consider it a good thing... Except one machine has 6 cores and the other 12 obscuring a serious threading issue on the newer architecture that would go unreported for a long time - A Windows process utilizing 100% of a single core is not utilizing 100% of the available scheduling/processor.

If someone can prove me wrong then I might look at adding this feature?

**Comment by Bartolomeus-649** [comment]
This was exactly the point I was trying to make, but you said it so much better.

Also, it's worth noting that a single threaded process on windows, can use more than 100% of one core, since the OS is multi threaded and any calls to the OS might utilize more then one thread/core in parallel.

One thing that might be interesting though, is if it would be possible to calculate some kind of "efficiency score" for a process, like is it using available resources or is it limiting it'self by, for example, only using one thread, or is it allocating resources which is never used. Fuzzy...not really sure what I mean by this myself... :)

**Comment by dmex** [comment]
> Also, it's worth noting that a single threaded process on windows, can use more than 100% of one core, since the OS is multi threaded and any calls to the OS might utilize more then one thread/core in parallel.

ntdll.dll creates a thread-pool with multiple threads during process initialization for loading the executable DLL dependencies in parallel for faster application startup and later uses the same thread pool at runtime for lots of kernel callbacks (KiUserApcDispatcher/KiUserCallbackDispatcher/KiUserExceptionDispatcher) which are invoked by other processes when querying things about your process (e.g. user32 window functions and debuggers etc...).

> is if it would be possible to calculate some kind of "efficiency score" for a process, like is it using available resources or is it limiting it'self by, for example, only using one thread, or is it allocating resources which is never used.

It's not possible to query the 'context' or operation of two different processes doing the exact same task and so these type of 'metrics' would be highly inaccurate.

For example:
ffmpeg with 10% utilization while encoding video and Libav with 4% utilization while encoding video; The "efficiency score" would show ffmpeg as more efficient than Libav which is correct.

Firefox with 10% utilization while playing video and Chrome with 4% utilization while playing video. In this example the "efficiency score" would show Firefox as more efficient than Chrome but it's the complete opposite.

This is also related to why Process Hacker does not show Fast/Slow/Good/Bad etc... type of metrics or automatically change anything on the machine (like most other programs do) because its not ever accurate and even if you code these assumptions they'll change in some future update to that program.

**Comment by 0xorial** [comment]
I have another use-case related to this functionality I think. I use PH on daily basis in my tray to have an overview of what is going on in my system (CPU history icon). Until now I was usually using a 2/4-core/thread CPU, so I can see when there is something going on (and not only after cooler ramps up :) ). Now I bought an 8/16-core/thread CPU, and in many cases a process would only take 1 thread. But in the tray it is not noticeable. I would be happy if there was an option to apply 'scaling' to that chart, just clipping above 100%. In my specific case I would set it up so that 1 full thread is taking 50% of height, for example.

**Comment by dmex** [comment]
Try adding the "CPU (relative)" columns to the process and threads tabs

**Comment by Mart-Bogdan** [comment]
@dmex I don't see column called "CPU (relative)", how to enable it?

![image](https://user-images.githubusercontent.com/775038/102930242-bcee6f00-44a4-11eb-9302-556be4fbca1d.png)

**Comment by Mart-Bogdan** [comment]
I see. It works in PH Nightly build https://processhacker.sourceforge.io/nightly.php

Perhps it's time to make new release? Last release was 4 years ago, but nightly seems to have lots of improvements.

**Comment by TETYYS** [comment]
> I see. It works in PH Nightly build https://processhacker.sourceforge.io/nightly.php
> 
> Perhps it's time to make new release? Last release was 4 years ago, but nightly seems to have lots of improvements.

https://github.com/processhacker/processhacker/issues/454
https://github.com/processhacker/processhacker/issues/415
