### ISSUE TITLE
Understanding RunAs TrustedInstaller

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#430]
I have a problem with the RunAs TrustedInstaller code, 
I ported it to my alternative GUI project, so it does the same as NTSTATUS RunAsCreateProcessThread
I have an own implementation of PhExecuteRunAsCommand2 which starts my tool as service,and communicated with it, giving it serialized version of PH_RUNAS_SERVICE_PARAMETERS parameters;
the tool running as service its privileges like process hacker does, SE_ASSIGNPRIMARYTOKEN_PRIVILEGE, etc,,,
than it de-serializes PH_RUNAS_SERVICE_PARAMETERS and gives it to PhInvokeRunAsService,
so far so good, the de-serialization seams correct, however the function fails in PhCreateProcessAsUser -> PhCreateProcessWin32Ex -> CreateProcessAsUser with an access denied error.

So why?! What have I missed?

EDIT: There must be something more fundamental wrong, the normal run as to start cmd.exe as system also fails at the same place. Is there a way to get more error information than jut PhGetLastWin32ErrorAsNtStatus something that would tell me the reason for the denied access?

EDIT2: any help sorting this bug out would be greatly appreciated, I just uploaded a new pre-release with the said issue: https://github.com/DavidXanatos/TaskExplorer/releases/tag/v0.0.9 in case soemone wahts to throw an eye or two onto the problem ;)

**Comment by AltF5** [comment]
I've created code to do this in C#. Would that help you? I see your project is in c++

**Comment by DavidXanatos** [comment]
I found the issue, while the de-serialization seamed correct, it was not :/ the SessionID was wrong, ...
Its of cause great that windows returns a access denied if the session id is wrong instead of returning an invalid parameter error or something like this.

**Comment by diversenok** [comment]
IMHO, when it comes to debugging, "invalid parameter" is the most useless error code ever since it just means "you are doing something wrong" ;)

**Comment by DavidXanatos** [comment]
Well, access denied is even more useless when the issue is not a missing permission but a parameter pointing to a non existent resource :p

**Comment by dmex** [comment]
> implementation of PhExecuteRunAsCommand2 which starts my tool as service,and communicated with it, giving it serialized version of PH_RUNAS_SERVICE_PARAMETERS parameters;
the tool running as service its privileges like process hacker does, SE_ASSIGNPRIMARYTOKEN_PRIVILEGE, etc,,,

I'm going to be removing all that code soon since it's unnecessary and obsoleted by some semi-documented CreateProcess flags... You actually don't need a service or even any privileges on Windows to create processes as other users (even as System) 😉

**Comment by diversenok** [comment]
@dmex, are you talking about `CreateProcessWithLogonW` and `CreateProcessWithTokenW`?
 
 - The first one works only for interactive logon and starts processes in the same session.
 - The second one still requires SeImpersonatePrivilege and also has some issues with starting processes in different sessions.

As far as I see, the only way to implement all current functionality without relying on a service instance is to perform a sequence of tricky operation while impersonating SYSTEM. For example, under some circumstances, it includes logging on the user with additional SIDs (the current logon SID). And I am still not sure about cross-session process creation without SeAssignPrimaryPrivilege (which ignores impersonation token). :thinking: 

Anyway, it sounds intriguing since I use a similar approach in my [TokenUniverse](https://github.com/diversenok/TokenUniverse) project, so I want to know more details. ;)

**Comment by AltF5** [comment]
@diversenok

NtCreateToken works great to do arbitrary anything. You “just” need SeCreateTokenPrivilege which is available “simply” by adding a user (Everyone?) via LSA User Rights and then batch logon (batch logon allows for on-the-fly changes) to get a token that can be impersonated against (and this NtCreateToken called). 

CPAU w AssignPrimary priv works well with a Thread token (impersonation token). I’ve tested it both in win7 and win10 in c#. Session switching just needs Tcb, which can be searched for from other process’ tokens that would then be “eligible” candidates to impersonate. Example: find a process running as SYSTEM user, and opt for System Integrity + highest privilege count (or specific privileges being sought like Tcb). This search method works well since all SYSTEM user processes will have Tcb (not create for CreateToken priv since that’s never assigned to anyone usually unless you added that user right from above and didn’t bother removing it lol).

Both techniques would require Impersonate priv to have ImpersonateLoggedOnUser work for a higher intrigrity level.

I’ve implemented both in C#.


Last note, is if just TrustedInstaller is desired without all the impersonating, thena call to LsaLogonUser allows ADDING new (not modifying existing) arbitrary groups to the returned token. But if that parameter is supplied then it too require Tcb and in that case you would need to impersonate to go from a High IL admin process to running a System IL process / tokening impersonating.

SeTcbPrivilege is quite and interesting bucket of things that are necessary for special high level only stuff to do.
Not required for:
- NtCreateToken (surprisingly)
- Impersonating to System IL
Is required for (just off the top of my brain)
- Changing Session ID of a duplicated token
- Changing IL (integrity) of a duplicated token
- calling LsaLogonUser if groups is supplied 
- WtsQueryUserToken (but it’s not like this is TokenLinkedToken if UAC is on with it being elevated, it’s not! Lol)

Just wanted to jot some stuff down here. Maybe useful to some. I’d like to eventually cleanup and decouple some c# code that does all this. It’s in a huge class I want to break out and add to github. James Forshaw, FuzzySec (b33f), and Matt Graeber were my inspirations :D (ps, dmex you should get a Twitter lol)

**Comment by DavidXanatos** [comment]
this project: https://github.com/lilkui/runasti uses CreateProcessWithTokenW to run any application as trusted installer, in fact I use this code in my tool for runas trustedinstaller instead fo the method used by proceshacker, as it did not require a service.

**Comment by diversenok** [comment]
@AltF5 

There are a lot of interesting approaches you are talking about, although NtCreateToken sounds like overkill, and temporarily changing privilege assignment in local security policy sounds like a hack ;)

> ... Example: find a process running as SYSTEM ... This search method works well since all SYSTEM user processes will have Tcb ...

You also need to perform some checks if you don't want to end up with a token of a restricted service https://github.com/hfiref0x/WinObjEx64/issues/14

> ... call to LsaLogonUser allows ADDING new (not modifying existing) arbitrary groups to the returned token.

Yeah, it is an extremely useful feature, especially when used with S4U logon. On the downside, looks like it can't add groups to passport accounts (SYSTEM, LocalService, and NetworkService), I tried it with LogonUserExExW, and it didn't work well.

> WtsQueryUserToken

This function performs absolutely insane access checks, and the requirement for Tcb is enforced only by wtsapi32.dll. You can directly call underlying WinStationQueryInformationW with WinStationUserToken information class which does not care about Tcb, although needs your user to be SYSTEM (even disabled state works). I can't imagine what kind of weird access checks it has internally.

Anyway, I am not sure that your list of suggestions suites Process Hacker, but I am planning to implement (or already did) most of these things in TokenUniverse. I'll invite you for testing when I release it :wink: 

@DavidXanatos
 
The code of this tool seems pretty straightforward, although its current version would not run without debug privilege (https://github.com/lilkui/runasti/pull/1).

**Comment by DavidXanatos** [comment]
@diversenok 
thanks for the fixes to runasti

**Comment by dmex** [comment]
@diversenok 

> are you talking about CreateProcessWithLogonW and CreateProcessWithTokenW?

No. CreateProcess spawns child processes with an duplicated token from the parent process. So what you do is use PROC_THREAD_ATTRIBUTE_PARENT_PROCESS and specify the TrustedInstaller service as the parent and CreateProcess will do all the work required to correctly spawn the process on the current desktop without you having to manually do/code everything yourself.

See the updated code here:
https://github.com/processhacker/plugins-extra/blob/master/TrustedInstallerPlugin/runas.c

> the only way to implement all current functionality without relying on a service instance is to perform a sequence of tricky operation while impersonating SYSTEM.

This is not the case. As an example you can right-click the System (pid 4) process (latest nightly build only) and select Miscellaneous > Run as this user to create processes with an identical token using just CreateProcess and without having to manually duplicate, modify or impersonate the System process - (which is impossible because the System process is a protected process that doesn't allow that level of access but you can OpenProcess system with PROCESS_CREATE_PROCESS and use it with CreateProcess)

**Comment by diversenok** [comment]
@dmex 
Oh, so you were talking about using a different approach to start another instance of PH as system and not about implementing the whole Run As functionality in the same process, right? That makes sense. :smile:
