### ISSUE TITLE
GPU load like in WIndows 10 task manager

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#433]
As its known there seam to be an issue with NVidia drivers which makes process hacker and process explorer not being able to display GPU usage... https://github.com/processhacker/processhacker/issues/381

But windows 10 task manager can do it properly in the other thread it was said:

> Task Manager uses performance counters for querying GPU information while Process Explorer/Process Hacker query GPU information directly from the dxgi kernel interface.

So why can't we do that for process hacker as well? We want a working solution and if its possible to use some performance counters than lets do that.

Is it known hot TaskMgr.exe is doing that or does it requirers some reverse engineering?

Windows 10 Task manager cna also show which CPU is used by any given application this is also very neat.

**Comment by Biswa96** [comment]
Just curious, did you try with Task Manager from Windows 7 or ReactOS?

**Comment by DavidXanatos** [comment]
Windows 7 task manager does not have a GPU usage graph, that's a windows 10 feature.
idk. about ReactOS

**Comment by dmex** [comment]
> As its known there seam to be an issue with NVidia drivers which makes process hacker and process explorer not being able to display GPU usage

It's a rare problem that will only happen after your nvidia installation is corrupted and it affects more than just GPU statistics.

> if its possible to use some performance counters than lets do that.

The problem is they're a major performance problem. Performance counters are string arrays (4-level deep multidimensional string array) and requires parsing the entire array for every process, every second and that causes major performance issues.

This is also why Task Manager performance is so terrible on Windows 10 because it's parsing thousands of strings for various performance counters and this takes anywhere from 5 to 20 seconds on startup and even more costs at runtime.

> So why can't we do that for process hacker as well?

The PerfMonPlugin implements performance counter support. You can add any counters to monitor via the plugin options: https://github.com/processhacker/plugins-extra/tree/master/PerfMonPlugin

> Task manager cna also show which CPU is used by any given application this is also very neat.

Process Hacker which has had this feature since Windows XP 😄 

You just hover the mouse over the CPU graph to see which application is utilising the most CPU and you can also double-click to open the properties for that process.

**Comment by DavidXanatos** [comment]
Thanks for the detailed infos :)

> It's a rare problem...

I have that issue on 3 to 4 machines (don't remember if i tested all4 or stopped at the 3rd).

And I don't see any issues with gaming performance on the two machines which serve partially also that purpose.
Also the NVidia GPU plugin seams to work just fine, only the generic GPU display is not working, what at least on my laptop that also has a Intel graphics is not a satisfying situation as there is no Intel GPU plugin that would work. :D

I will debug the issue further using a clean and fresh windows 10 ToGo installation and provide more detailed feedback.

Given how prevalent the issue is for me i thought it would be a good idea to do it the Task Manager way, at least as fallback. I understand the rational of wanting to do things efficiently the right way. But there is also the rational that users expect things to work no mater what :D
So I'm thinking of checking after start if the efficient API is working and if not showing the user a window offering him to switch to the Performance counter way and informing him about the performance hit, plus an option to "not show this message again".

> The PerfMonPlugin implements performance counter support. 

Ah great! Will check that one out ASAP.

Cheers and keep up the good work!
David X.

**Comment by DavidXanatos** [comment]
I was playing around with counters in process hacker but couldn't find one that would work as expected,
does anyone know which one are the right once?
