### ISSUE TITLE
How to solve errors when building with Visual Studio 2017?

### ISSUE THREAD

**Issue by tomasorti** [processhacker/processhacker#438]
When trying to build PH from master with Visual Studio 2017:
![image](https://user-images.githubusercontent.com/2485147/61015661-d2dda200-a38c-11e9-8ef2-93168d9819ab.png)

I get this errors:
![image](https://user-images.githubusercontent.com/2485147/61015688-f6a0e800-a38c-11e9-933a-6de944ae5d4f.png)

A `Project | Retarget solution`, produces the same errors:
![image](https://user-images.githubusercontent.com/2485147/61015757-42539180-a38d-11e9-95d5-a96ae7bde651.png)

How should I build it?
Thanks in advance.

**Comment by MagicAndre1981** [comment]
you now [need VS2019](https://github.com/processhacker/processhacker/commit/e4b65db54078497a10a1d616e384e3a93c20f6ae)

**Comment by DavidXanatos** [comment]
For all aplicable projects just go to properties, general properties, change platform tool-set to the version you have installed.

![image](https://user-images.githubusercontent.com/3890945/61053783-82972c00-a3ee-11e9-929c-8811bc3013da.png)

you should be able to choose vs2017 and it should built woth it just fine.

**Comment by MagicAndre1981** [comment]
yes, but on each update you will get git pull issues about conflicts

**Comment by dmex** [comment]
> you will get git pull issues about conflicts

No. You only get conflicts when the solution files change (which is very rare).

**Comment by MagicAndre1981** [comment]
can you please create 2 csproj files for 2017 and 2019 to avoid this issue? So everyone can compile it with the version he wants. 2019 is unusable. Currently you can fix it, but Microsoft will sooner or later break all extensions that fix the UI changes.

**Comment by dmex** [comment]
2019 is backwards compatible and you can easily change it from the Retarget Solution menu?

**Comment by tomasorti** [comment]
> 2019 is backwards compatible and you can easily change it from the Retarget Solution menu?

Question mark is suspect of causing confusion...

**Comment by tomasorti** [comment]
> you should be able to choose vs2017 and it should built woth it just fine.

I did that and still get the same error:
![image](https://user-images.githubusercontent.com/2485147/61165429-b7a39b80-a520-11e9-94d5-4b68290e8ebc.png)

See:
![image](https://user-images.githubusercontent.com/2485147/61165433-cee28900-a520-11e9-9d56-1be478c95035.png)

**Comment by tomasorti** [comment]
Mmm... 
I updated Visual Studio 2017 from version 15.9.5 to 15.9.14
Then changed the platform toolset on ProcessHacker, phlib & peview projects.
And now I am getting this:
![image](https://user-images.githubusercontent.com/2485147/61170112-07a45180-a565-11e9-9f69-dca3daf4cc0e.png)

Though Visual Studio Installer tells me I have Windows SDK version 10.0...
At least it shows several versions of it:
![image](https://user-images.githubusercontent.com/2485147/61170159-54882800-a565-11e9-8c2f-846f5df771aa.png)

Any hints, help how to solve this?

**Comment by Biswa96** [comment]
Visual Studio Installer --> Individual components --> Compilers, build tools and runtimes --> MSVC v142 (and spectra)

**Comment by tomasorti** [comment]
Thanks, but there is no such item **MSVC v142** or similar in **Compilers, build tools and runtimes**.
Any other recommendation/hint, please?

![image](https://user-images.githubusercontent.com/2485147/61186875-bbdbd000-a66a-11e9-9346-601694a3960a.png)

**Comment by MagicAndre1981** [comment]
you need to run [Installer for Build Tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019). Installed over 5GB of data to get v142 installed 🤦‍♂️

**Comment by MagicAndre1981** [comment]
> Mmm...
> I updated Visual Studio 2017 from version 15.9.5 to 15.9.14
> Then changed the platform toolset on ProcessHacker, phlib & peview projects.
> And now I am getting this:
> ![image](https://user-images.githubusercontent.com/2485147/61170112-07a45180-a565-11e9-9f69-dca3daf4cc0e.png)
> 
> Any hints, help how to solve this?

this is a change in VS2019 to use latest Win10 SDK. Change it to latest SDK you have installed like 10.0.17763.0 or 10.0.18362.0

**Comment by tomasorti** [comment]
I just quit trying to use VS2017 and install VS2019, which compiled ProcessHacker fine.

**Comment by MagicAndre1981** [comment]
yes this is best, but VS2019 UI (compact menu, Start Window shit, unusable "Create New Project" dialog) sucks.

**Comment by DavidXanatos** [comment]
> 
> 
> yes this is best, but VS2019 UI (compact menu, Start Window shit, unusable "Create New Project" dialog) sucks.

Are there any extensions to make it suck less?

**Comment by MagicAndre1981** [comment]
> Are there any extensions to make it suck less?

but but in each update Microsoft breaks them because currently all old parts are still part of VS2019, but hidden and sooner or later Microsoft will remove old code:

- Startpage: https://marketplace.visualstudio.com/items?itemName=JanKucera.StartPageOnStartup
- New Project dialog: https://marketplace.visualstudio.com/items?itemName=softworkz.SwitchProjectDialog
- compact menu can be disabled inbox in vs options, but gets reseted by Microsoft very often and removing the Titlebar breaks other [extensions like this one](https://marketplace.visualstudio.com/items?itemName=mayerwin.RenameVisualStudioWindowTitle)

**Comment by dmex** [comment]
I still use VS2017 because 2019 constantly resets all my preferences. The repository needs to be using 2019 because of the nightly builds and also because that's whats available on the MS site and whats now the default for new updates and features (plus its what new users will download by default).

I don't quite understand why you're all having so many issues using 2017 when 2019 is backwards compatible and you can just change the project from the retarget menu?

In the last 10 years I've updated the Process Hacker project from 2008 -> 2010 -> 2012 -> 2013 -> 2015 -> 2017 and now 2019... Its easier to use older versions now than its ever been in previous versions 🤔

**Comment by MagicAndre1981** [comment]
the Win10 SDK 10.0 entry is a breaking change between 2017 and 2019. VS2017 doesn't understand that [10.0 means last version](https://walbourn.github.io/windows-10-may-2019-update/) and you can see that @tomasorti struggled at this change.
