### ISSUE TITLE
PHNT_VERSION correction in READ.ME

### ISSUE THREAD

**Issue by BigJim** [processhacker/processhacker#442]
Small error in the "READ.ME" file where it says:
> By default, only definitions present in Windows XP are included into your program.

As evident by the code. the default is actually Windows 7 now:
`#ifndef PHNT_VERSION
#define PHNT_VERSION PHNT_WIN7
#endif`

Just needs to be corrected to reflect the current code with:
> By default, only definitions present in Windows 7 are included into your program.

**Thanks for this great set of headers!**
It's a headache to try to use the "windows.h" and "winternl.h" for desktop use since it's missing many things and/or only included limited defines, etc. Not to mention all the version dependencies. Sure beats making ones own or trying to use one of the many incomplete "ntdll.h" header sources off the net.

**Comment by dmex** [comment]
> Small error in the "READ.ME" file where it says:

This is true if you've included the correct headers but in the past most people don't refer to the readme before using the headers and try directly including the specific header they needed and thus end up with XP defaults.

> As evident by the code. the default is actually Windows 7 

Yes only when you've included the phnt.h header otherwise you get XP defaults. We would need to remove the ifdefs for Win7 to actually make it the real default?

**Comment by BigJim** [comment]
I noticed if I pressed F12 (or the "Go" button in VisualAssist) on _PHNT_VERSION_ that the default was actually _PHNT_WIN7_ not _PHNT_WINXP_. Then verified by grepping all instances of _PHNT_VERSION_.
Not a big deal at all, just wanted to point it out in case it was a documentation error the READ.ME.
Feel free to close this issue et al.

FYI I use your headers with the VS2017 "ntdll.lib" (might require the Windows 10 WDK) to access "ntdll.dll" exports from DLL and exe projects. Excellent solution for NT internals!

**Comment by dmex** [comment]
> I use your headers with the VS2017 "ntdll.lib"

The headers are part of a larger library (PHLIB) which uses the same ntdll.lib import but with a GPL license:
https://raw.githubusercontent.com/processhacker/processhacker/master/phlib/include/phbase.h

There's also a ntdllp.lib with private symbols for linking without the CRT.

> the default was actually PHNT_WIN7 not PHNT_WINXP

This is only true when phnt.h was included otherwise its 0 and the ifdefs default to WINXP
