### ISSUE TITLE
Getting WSL process's version info causes PH to go into a never ending loop

### ISSUE THREAD

**Issue by yossizahn** [processhacker/processhacker#483]
Starting a wsl bash shell causes PH to go into spasms... I see many wsl processes spawned by PH in quick succession in a never ending loop. This causes my CPU usage to spike to 100%. 
Procmon recording:
![image](https://user-images.githubusercontent.com/19174667/66903772-be541a00-f00b-11e9-9c9e-70f4ffae431b.png)

Disabling WSL support mitigates this behavior.

Related issue: #393

If I understand correctly, the issue seems to be that `dpkg -S /init`  fails (probably because `/init` doesn't belong to any package). _This failing result is not cached._ For each wsl process launched by PH, a parallel `init` process is launched by Windows. This in turn causes PH to launch more wsl processes in order to retrieve the (non-existent) version info...

**Comment by dmex** [comment]
> the issue seems to be that dpkg -S /init fails (probably because /init doesn't belong to any package).

the /init binary gets injected/copied into the disto folder by wsl.exe during initialization of the Linux distro hence there isn't any 'owner' package we can query for version information.

The first public version of the code included a check for /init replacing it with /sbin/init:
https://github.com/processhacker/processhacker/blob/830487082dc3b09cb2cf67caaa732b9279da2dfc/phlib/wslsup.c#L161-L166

The problem is the /sbin/init package is owned by systemd (which doesn't even work with WSL) and so it was removed because its not the correct version information (which should be Microsoft).

> This failing result is not cached.

Erroneous results should never be cached?

There is a hard limit of 1 query for each WSL process. If the WSL query succeeds or fails there isn't ever a second query.

**Comment by yossizahn** [comment]
> and so it was removed because its not the correct version information (which should be Microsoft).

agreed...
> Erroneous results should never be cached?

This is not an erroneous result. This is a valid result that indicates that no version information is available. The fact that there is no version info available should be cached.

> There is a hard limit of 1 query for each WSL process. If the WSL query succeeds or fails there isn't ever a second query.

That may be true, but each attempt at querying dpkg/rpm for info will spawn more `init` processes which will in turn spawn more `dpkg-quey` etc. processes leading to high CPU usage.

**Comment by dmex** [comment]
@yossizahn 

I've revered the check on /init with commit https://github.com/processhacker/processhacker/commit/ffea1dc8e2582e2cd76811bf061df4b1754858f5

**Comment by yossizahn** [comment]
> Does it fix the issue?

Yes. Thanks.

**Comment by dmex** [comment]
Not sure what happened to my original comment back in October :/

> Yes. Thanks.

Thanks!

**Comment by yossizahn** [comment]
Hi, 
Issue has returned :(

**Comment by Biswa96** [comment]
I have done some digging in WSL area. If you need any information I can provide some secrets. 🤫

**Comment by yossizahn** [comment]
Quick fix! Thanks!
