### ISSUE TITLE
Can't build CustomBuildTool after ea273f54

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#485]
```
1>------ Build started: Project: CustomBuildTool, Configuration: Debug x64 ------
1>Source Files\HeaderGen.cs(30,18,30,28): error CS0101: The namespace 'CustomBuildTool' already contains a definition for 'HeaderFile'
1>Source Files\HeaderGen.cs(37,18,37,27): error CS0101: The namespace 'CustomBuildTool' already contains a definition for 'HeaderGen'
1>Source Files\HeaderGen.cs(46,16,46,25): error CS0111: Type 'HeaderGen' already defines a member called '.ctor' with the same parameter types
1>Source Files\HeaderGen.cs(88,34,88,50): error CS0111: Type 'HeaderGen' already defines a member called 'OrderHeaderFiles' with the same parameter types
1>Source Files\HeaderGen.cs(99,22,99,38): error CS0111: Type 'HeaderGen' already defines a member called 'OrderHeaderFiles' with the same parameter types
1>Source Files\HeaderGen.cs(112,30,112,48): error CS0111: Type 'HeaderGen' already defines a member called 'ProcessHeaderLines' with the same parameter types
1>Source Files\HeaderGen.cs(160,21,160,28): error CS0111: Type 'HeaderGen' already defines a member called 'Execute' with the same parameter types
1>Done building project "CustomBuildTool.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
![111](https://user-images.githubusercontent.com/24621645/67128189-9929fc00-f203-11e9-81ef-adffd44223fa.png)

**Comment by VictorVG** [comment]
Also, I install both MS .NET Core 3.0 SDK - x86 and x64, add to compiler .NET cross tools, rebooted the OS several times, but eventually ran into a compiler message

Error NETSDK1004 resource file ".\tools\CustomBuildTool\obj\project.assets.json" was not found. Repair the NuGet package to create it. CustomBuildTool c:\program files\dotnet\sdk\3.0.100\Sdks\ Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets 234

It seems that the reason is spaces in the paths. We'll have to configure the OS to eliminate other people's flaws ...

**Comment by dmex** [comment]
@skipik 

Fixed

@VictorVG 

"not available in the following package sources: Microsoft Visual Studio Offline Packages"

You have to be online to restore nuget packages.

**Comment by VictorVG** [comment]
BUT! And I manually searched the whole machine and eventually made mv -f CustomBuildTools.exe CBT.exe & cp -f CBT.exe ./tools\CustomBuildTool/bin/Release/ and adjusted the line of my bld.cmd script with the ability to easily roll back.

And since, due to chance, I had to update the source code in plugins-extra, I again had to fix FirewallMonitorPlugin.vcxproj line 26:
  <WindowsTargetPlatformVersion> 10.0.17763.0 </WindowsTargetPlatformVersion>

on
     <WindowsTargetPlatformVersion> 10.0.18362.0 </WindowsTargetPlatformVersion>

otherwise it is not going with error C2065 in monitor.c line 548. I assembled it successfully, but only tired from fatigue, skipik wrote how to fix the assembly in that situation. :)
