### ISSUE TITLE
UDP traffic not accounted for

### ISSUE THREAD

**Issue by kilves76** [processhacker/processhacker#532]
Using the 2019 Dec 23 nightly but UDP network traffic is still not accounted for. I know nothing about Windows programming but udp connections do have the ASSURED state. If this is not available then a user configurable timeout for assured would do, i'd set this for 180 seconds.

Please, it's pretty terrible to see only 5-10% of the traffic accounted for.

Otherwise the Network tab looks pretty good, countries stay sorted.
WHEN the Country tab is selected, it'd be pretty great to be able to Pin a certain country and have the country list be displayed with this country at the top. I don't mean resorting, just have the alphabetically sorted country list always keep the pinned country starting at top row, whichever direction the whole list is sorted with.

**Comment by kilves76** [comment]
A bit early with my praise for the country list sorting, why is Spain sorted after China? It's MOSTLY alphabetical... :)

**Comment by dmex** [comment]
>  udp connections do have the ASSURED state.

The GetExtendedUdpTable API doesn't have this information.

> terrible to see only 5-10% of the traffic accounted for

It's always accounted for the process on the statistics page but not always accounted for individual connections you see on the network tab because ETW doesn't always have the correct to/from address for UDP statistics but always has the correct PID.

> Pin a certain country and have the country list be displayed with this country at the top

I have a patch for showing the estimated distance based on geoip. It would be more logical to sort via distance than by specific countries (especially to avoid the appearance of R and favoritism)?

**Comment by kilves76** [comment]
Was thinking of NetworkTrafficView by Nirsoft but forgot it's using winpcap (or rather npcap today), maybe it makes a difference, it has udp conversations view since v2.25. Then again i wouldn't mind installing npcap to get this functionality to PH2.

**Comment by dmex** [comment]
There were some fixes for the UDP traffic counters in recent nightly builds but they might not include all traffic for that process but instead show as traffic for the System process.

> Then again i wouldn't mind installing npcap to get this functionality to PH2.

npcap is outside the scope of the project because of its traffic capture/inspection.
