### ISSUE TITLE
VAC still a problem?

### ISSUE THREAD

**Issue by Marctraider** [processhacker/processhacker#554]
Was running a nightly from half a year/year back and recently got a warning and got kicked from matches.

Does latest nightly run fine? Or is the offending element able to be disabled? 

I assume it is the kernel driver causing it?

**Comment by dmex** [comment]
> Does latest nightly run fine?

Yes. I last checked on the 28th of December, 2019 and it worked fine. 

> a nightly from half a year/year back

Please update to the latest nightly build and let me know if you're still having issues. I have direct contacts with Valve and can discuss issues with them anytime.

>  is the offending element able to be disabled?

No. Valve and all other Anticheat software doesn't use any generic scanning for some sort of generic feature because of there are too many false positives for other Windows software (especially security software) using the exact same API functions on Windows just like Process Hacker does.

If they've started blocking our binaries then even removing all the code won't resolve the issue.

> I assume it is the kernel driver causing it?

No. Anticheat software uses the [ObRegisterCallbacks function](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-obregistercallbacks) to limit our kernel driver without having to outright blacklist our driver or requiring us to make changes to our driver.

Microsoft added the ObRegisterCallbacks function back in 2006 for this exact reason allowing tools like Process Hacker to coexist peacefully with antivirus/anticheat software requirements.

If you ever have issues then please report this to us here on Github so we can follow up with Valve or other companies - sometimes they hire people without any knowledge or experience and they make stupid decisions that are unnecessary 👍

**Comment by Marctraider** [comment]
Thank you for taking the time to respond.

However I'm still not 100% convinced, as I read that there was no communication with valve at all? or this could be years ago im not sure.

Also processhacker is still listed on steam's website of programs that could cause problems. Is this because they are not stating version numbers? Why is this not communicated then? Like xxx version?

Thanks!

**Comment by dmex** [comment]
> I read that there was no communication with valve at all? or this could be years ago im not sure.

Things have changed.

> processhacker is still listed on steam's website of programs that could cause problems. Is this because they are not stating version numbers? Like xxx version? Why is this not communicated then? 

They don't mention versions for the other products even things like powershell. It might be a policy to confuse cheaters by limiting the amount of information about what VAC does.

You can still get kicked for using Process Hacker but its extremely rare these days and you would have to be doing/running a few things to trigger the kick.
