### ISSUE TITLE
Trojan:Win32/Casdet!rfn threat detected by Windows Defender in the nightly builds

### ISSUE THREAD

**Issue by microdee** [processhacker/processhacker#564]
As the title says, downloading nightly builds now are impossible because Windows Defender and in cooperation chrome immediately deletes the file to protect the system. I trust process hacker and by nature it's not a safe program indeed for people who don't know what they're doing, so I know this is only a misunderstanding.

**Comment by microdee** [comment]
On that note Windows Defender also detects Trojan:Win32/Detplock in Online Checks plugin

**Comment by sa-shiro** [comment]
yea me too, but i guess its safe right? :D fkin windefender wants to prevent us to use phacker ^^

**Comment by microdee** [comment]
I've been using PH for ages, it has been safe to use, I can completely endorse it, this popped up today. Unfortunately even when I make an exception for the PH setup in Windows Defender, when it wants to do the admin bit WD completely blocks it in UAC, without the option "I really know what I'm doing".

As a side note, please understand that disabling or weakening WD or UAC is not a solution, they are very important security tools when they're not crying wolf. PH can also be a really powerful sysadmin tool too, and if one sees these alerts, they will not give PH a second chance ever again.

**Comment by Biswa96** [comment]
This issue is similar with this mega thread https://github.com/processhacker/processhacker/issues/454. Please subscribe to that issue to get future information.

**Comment by microdee** [comment]
oh thanks, didn't notice that thread

**Comment by dmex** [comment]
I can't submit false positives to Microsoft via the WDSI portal after Microsoft declared Process Hacker malicious and banned my account (see #454), 

Someone else has to submit the files here and reply here with the submission details: 
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by kdlslyv** [comment]
I've submitted the latest nightly, i'll reply with updates about the submission.

**Comment by KaoDome** [comment]
I had submitted the latest nightly yesterday along with a detailed information on what the program is about (just in case, mentioning their own Process Explorer too), with links to the main site, the GitHub project and the AppVeyor site. I also stated that while nightly builds are not digitally signed, the (kernel-mode?) driver is and its signature is still valid because it was countersigned.

I also stated that Process Hacker is the only application I know that ships hardened like that, not only the usual DEP and ASLR (which some apps even miss) but CFGuard is enabled, restricts remote image location loading, and only approved signatures, etc.

It seemed not to matter, their resolution was that it fits the criteria to be malware and it'll stay as it is: https://www.microsoft.com/en-us/wdsi/submission/645d8857-7058-4e89-b329-8b358f1fdccc

I wonder what it is that's triggering their engine to detect it as such. I mean, come on... the code is open and they could check that it ain't malicious at all.

I couldn't find any more info on what the _Win32/Casdet_ malware family is about, only Defender appears to be using that nomenclature, but a quick search showed FileZilla to have been flagged as such too at least once: https://forum.filezilla-project.org/viewtopic.php?f=2&t=51929

I also submitted the sample to VirusTotal as well, where we can see not only Defender picks it up but several others as well, but from what I could see the detections were based on heuristics and not conclusive: https://www.virustotal.com/gui/file/7040a1f048a8153f7488dc9e6aecbcc3339d13aad00acc8eb80963aa667793ae/detection

Just to see how they'd react if it weren't the setup, but the program itself, I just submitted an archive of the latest build (without its setup, i.e. after it being installed archiving all of the files minus the setup) and the results are different (as expected), but Microsoft's Defender now detects it as _Win32/Wacatac.C!ml_: https://www.virustotal.com/gui/file/1eaabcf5c7e7fba2f7ff58e4af0cf77fd839fc9eab9fcb1f170657e61ccfc111/detection

If it were archived and set to run automatically after extraction (same settings more or less, only used an SFX with autorun when archiving) again different detections by the vendors, but this time Defender detected it just as if it were only archived, _Win32/Wacatac.C!ml_: https://www.virustotal.com/gui/file/6b15613c0db0ed31108847a7e571d3d89ee36d6e8a82c8635b1e3c4f17c46a37/detection

If those "!ml" in the Defender detections stand for machine learning, I could understand it being flagged because of what the program is capable of doing... but aren't WDSI submissions checked by people and not automated?

**Comment by microdee** [comment]
WD be like
"halt! state your business!" 
"mine some shady cryptocurrency in the background and send keystrokes to a russian server"
"right this way sir!... halt! state your business!"
"allow the user to see processes, resources and manage them, by the way here's my source..." 
"you sicken me! cease this scum!"

**Comment by kdlslyv** [comment]
![PH_detection_removed](https://user-images.githubusercontent.com/13890151/75290808-53b8b380-5821-11ea-8383-00355edd6173.png)

I didn't submit the setup, however the following entries were detected:

- Trojan:Win32/Wacatac.D!ml
- Trojan:Win32/Wacatac.C!ml 
- Trojan:Win32/Wacatac.B!ml 
- Trojan:Win32/Fuery.C!cl 
- Trojan:Win32/Detplock 

Hopefully the situation will eventually relax if everyone starts submitting enough reports on their own :)

**Comment by Shadoward12** [comment]
I don't use PH but google led me here when searching for "Casdet!rfn." WD detected this when I attempted to install Cheat Engine and had me freaking out.

**Comment by dmex** [comment]
@Shadoward12 

Here's what I was able to find:

September, 2019 - [NULS blockchain project](https://nuls.community/d/615-trojan-win32-casdet-rfn-nuls-wallet-win64-1-3-0-zip)
October, 2019 - [WAMP uniform server project](http://forum.uniformserver.com/topic/3319-trojan-in-windows-binary-unpacker/)
January, 2020 - [FileZilla project](https://forum.filezilla-project.org/viewtopic.php?f=2&t=51929)
January, 2020 - [Android Toolbox project for Amazon Fire](https://forum.xda-developers.com/showpost.php?p=81453889&postcount=1885)
February, 2020 - Process Hacker
March, 2020 - Cheat Engine

The only commonality here is they're all open-source since none of these projects shares any source code, modules or anything that would indicate the actual issue plus the dates between signatures are too far apart.

**Comment by microdee** [comment]
maybe programs will be called Casdet trojan, which Microsoft just wants to get rid of?

**Comment by microdee** [comment]
Just tried nightly builds again and WD now doesn't complain anymore, for me at least.

**Comment by linuxandria** [comment]
My college is blocking the download site and it cites malware as the reason (they appear to use OpenDNS)

**Comment by dmex** [comment]
@linuxandria 

Can you please add that information about OpenDNS into this topic: #556

**Comment by sZebuddi** [comment]
Just Posted submission to ms,  as I program in a niche language This is always the problem  sometimes as loopy as it sounds  a 1 liner call msgbox()    contains a virus  " you shall not pass" omg
Zebuddi.


Submission details Refresh

 Please bookmark this page if you wish to monitor the progress of your submission.
processhacker-build-setup(1).exe

Submission ID: 13715bab-3861-48cd-ac1f-f0301dab4187

Status: Submitted

Submitted by: anonymous@microsoft.com

Submitted: Mar 30, 2020 17:25:28

User Opinion: Incorrect detection

Analyst comments:


                No analyst comment provided.

**Comment by dmex** [comment]
We'll use #454 for tracking issues with Microsoft.
