### ISSUE TITLE
Small graphs are broken

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#575]
I don't know what happened. It all happened after I restarted PH last night (because Avast! is bs and busy-waits the rest of my CPU constantly)

![image](https://user-images.githubusercontent.com/133706/76933925-e6b3ad80-68f6-11ea-8cb2-1879839fa045.png)

I'm on the latest version
![image](https://user-images.githubusercontent.com/133706/76933964-00ed8b80-68f7-11ea-9d8a-57e834414384.png)

(_Please make About window On Top & make text selectable or copyable for bug report purposes_)

**Comment by dmex** [comment]
> It all happened after I restarted PH last night

If you reset the settings does it still happen? 

1) rename settings.xml to settings.bak
2) start process hacker and re-enable the graphs
3) exit process and restore settings.bak to settings.xml

> (because Avast! is bs and busy-waits the rest of my CPU constantly)

You might need to disable the Avast hypervisor since its bypassing Kernel Patch Protection (KPP) and hooking the kernel.

**Comment by stdedos** [comment]
> > It all happened after I restarted PH last night
> 
> If you reset the settings does it still happen?
> 
> 1. rename settings.xml to settings.bak
> 2. start process hacker and re-enable the graphs
> 3. exit process and restore settings.bak to settings.xml

I resumed my system from hibernation and now the graphs work 😕 but I can replicate it accurately by closing and re-opening PH.

Your approach seems to fix the issue permantely. ... As long as I keep re-setting and re-applying the settings.

I'm attaching my configuration [PH_config.zip](https://github.com/processhacker/processhacker/files/4350704/PH_config.zip)

* `def` are the defaults + Graph activated
* `orig` was the configuration prior to this
* the plain one is the one after all of this ^^ plus closing PH (I think you flush the settings only at exit)

-----

However, in doing so, I have two gifts for you:

[PH.dmp.zip](https://github.com/processhacker/processhacker/files/4350679/PH.dmp.zip)

-----

> > (because Avast! is bs and busy-waits the rest of my CPU constantly)
> 
> You might need to disable the Avast hypervisor since its bypassing Kernel Patch Protection (KPP) and hooking the kernel.

I would like to investigate that alternative ... sometimes I just want to kill it so much; however, the hooks it deploys block even _sneezing_ at it.

**Comment by dmex** [comment]
I wasn't able to reproduce the issue with your settings. 

After reviewing the mini-dumps what I suspect is happening... Avast is suspending the main process provider thread when we query process information from the Avast kernel hooks (for some type of dumb check) which introduces a race condition/deadlock between the provider thread and the main window thread drawing graph data (because the threads should never get suspended introducing deadlocks).

I've added extra consistency checking to the graphs that should prevent the race condition.. Try updating to v3.0.2953 and checking if that version fixes the issue.

**Comment by stdedos** [comment]
No, I can still trigger it :/

**Comment by dmex** [comment]
> No, I can still trigger it :/

Can you reproduce the issue on a second machine or after uninstalling Avast? 

I'm just unsure why I can't reproduce it on my laptop but then again I don't use third party AV.

**Comment by stdedos** [comment]
I've only seen it on my machine, so I'll go with no.

I'm closing the verge of removing it, but not yet. If I do it "just to debug this  issue" it's probably not going in again, so, I'll hold off for now.
