### ISSUE TITLE
BSOD when searching for open handles consistently

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#581]
In the same system as https://github.com/processhacker/processhacker/issues/572, searching for a file handle to unlock, consistently gives me:

```
# ProcessHacker check open file handles
032320-5906-01.dmp	23/3/2020 3:36:57 μμ	UNEXPECTED_KERNEL_MODE_TRAP	0x0000007f	00000000`00000008	ffffc280`f1cc9f50	ffff8402`ad111fe0	fffff80e`fb8ac1e5	ndis.sys	ndis.sys+ac1e5	Network Driver Interface Specification (NDIS)	Microsoft® Windows® Operating System	Microsoft Corporation	10.0.17134.1 (WinBuild.160101.0800)	x64	ntoskrnl.exe+1aabb0					C:\Windows\Minidump\032320-5906-01.dmp	4	15	17134	1.169.884	23/3/2020 3:38:50 μμ
```

Unfortunately, I cannot get the `C:\Windows\Minidump\032320-5906-01.dmp` file (if that would help)

**Comment by dmex** [comment]
Which version of Process Hacker?

**Comment by stdedos** [comment]
Unfortunately, I cannot open PH (#582), and there are no extended properties on the PH executable (Is that really the case / possible???).
![image](https://user-images.githubusercontent.com/133706/77735237-dc8a6100-7012-11ea-9fb9-ffae83be0423.png)

Is there a command-line flag to do this from the terminal? (`-v,(-)-version,/?,-?` don't work)

**Comment by dmex** [comment]
I can't reproduce this blue screen and haven't seen any other cases reported. Our driver code hasn't changed since 2016 and doesn't do anything with ndis and since your blue screen has only just appeared recently it would indicate its caused by some third party.

1) You have faulty hardware.
2) You have a faulty network driver.
3) Your anti-virus is hooking ndis.sys and there is a bug crashing the machine when we query its handle.
4) A kernel rootkit hooking ndis.sys and crashing the machine when we query its handle.

> Unfortunately, there is something else that's preventing PH to launch (without any explanation)

I would assume its a kernel rootkit preventing the application from launching.

**Comment by stdedos** [comment]
Downloading a new build still doesn't show any command line flags or file properties though

**Comment by dmex** [comment]
> still doesn't show any command line flags 

The only prompt from the command line is -help

> or file properties

File properties were disabled last year after malware was using those strings to block the binary.

**Comment by dmex** [comment]
I can't reproduce it and there hasn't been any additional reports. I would assume its a faulty network driver or kernel rootkit/hook bug checking the machine when we query one of its handles (which is a common anti-debug technique used by rootkits).
