### ISSUE TITLE
[Riot VANGUARD?] Unable to load the kernel driver.

### ISSUE THREAD

**Issue by Puncia** [processhacker/processhacker#602]
I updated to version 3.0.3041 and now every time I click on "Show detail for all processes" or run Process Hacker as Administrator I get this message:

![Process Hacker](https://i.imgur.com/kkOu9OW.png)

"The driver was not loaded because it failed its initialization call."

I tried multiple times to install/uninstall but without succeeding.
I couldn't find any solution online regarding this particular message; any help is appreciated.

**Comment by Biswa96** [comment]
Does the `kprocesshacker.sys` file present in Process Hacker installation folder? Is there any antivirus program that can delete it?

**Comment by Puncia** [comment]
Yes, `kprocesshacker.sys` is present in the installation folder. I only use Windows Defender, and it does not detect it as virus. I also made sure the folder is whitelisted to make sure:

![](https://i.imgur.com/NyuPPUa.png)

**Comment by Puncia** [comment]
Update: I think it's because of Riot VANGUARD. After uninstalling it, I no longer encounter the error message.

**Comment by dmex** [comment]
I discovered a critical security issue in the Riot games kernel driver allowing malicious attackers to block debuggers, system utilities, and other applications with absolutely zero effort required.

The exploit was reported 19 days ago but the company still hasn't responded:

![image](https://user-images.githubusercontent.com/1306177/82171940-10e01680-990c-11ea-9949-d1fdf1e3ed1b.png)

> "The driver was not loaded because it failed its initialization call."

The current LTS stable build v2.39 of Process Hacker has the exact same issue but you won't see an error dialog because of how the Riot Games kernel driver has blocked the Process Hacker driver.

The nightly builds don't have the same attack vector and will correctly show an error dialog but won't be able to remedy the error in the case of malware/spyware exploiting the Riot games kernel driver - that will probably require rebuilding our kernel driver from scratch with new configuration and digital certificates to avoid the security issue in the Riot games kernel driver.

**Comment by DavidXanatos** [comment]
imho we need a mechanism to rename the driver service and the IPC pipe it uses for communication with PH

avast iirc also just opens an own dummy pipe on the name PH wants to use

**Comment by dmex** [comment]
>  because of Riot VANGUARD

The RIOT kernel driver can be misused in malicious attacks against Process Hacker since it hard-coded our device strings in their driver and executes standalone at boot without requiring Riot games software installed.

Malicious software can xcopy distribute the riot kernel driver to machines without riot software installed, load their kernel driver and automatically block Process Hacker on the machine silently.

The company has practically ignored this issue:
![image](https://user-images.githubusercontent.com/1306177/82894089-5d26f880-9f95-11ea-8710-5d1c15f22441.png)



The nightly builds will correctly show an error dialog when this occurs but the current stable 2.39 won't show an error dialog.

> we need a mechanism to rename the driver service and the IPC pipe it uses for communication with PH

This is the only way to stop malicious software using previous versions of the Riot kernel driver to block Process Hacker.

> avast iirc also just opens an own dummy pipe on the name

This is known as a squatting attack.

> the name PH wants to use

The source code for those names is under GPL3 licence so they're violating the GPL3 by including those strings in their product. They're supposed to be using the SeRegisterImageVerificationCallback function and check the digital signature of the driver since digital signature strings are not under GPL licence.

**Comment by DavidXanatos** [comment]
haha... claiming copyright on a name string is a bold move but if it scaries them into compliance, why now.

But in any case having a flexible device name may be good to have...

**Comment by dmex** [comment]
> claiming copyright on a name string is a bold move

Text has copyright. Try copying html, javascript, LUA and other strings on your machine into a product and selling it for profit without licencing those works.

>  if it scaries them into compliance

I can think of many other reasons.

* The project is open source and name squatting on our device object won't stop anyone recompiling the source with a different name and so targeting those strings is not effective. It does however stop me recompiling the driver because our certificate has expired and will take time and money to fix an issue created by their idiocy.

* Loading the kernel driver requires administrative privileges. Targeting Process Hacker because of things administrators can do with administrator privileges doesn't work: https://devblogs.microsoft.com/oldnewthing/20200518-00/?p=103767

* They could have emailed saying 'we think this is insecure' and I could've provided advice on how to properly fix the issues they were trying to fix before targeting our driver. EAC, VAC and BattlEye don't block our driver after the conversations we've had. I know the issue Riot where trying to avoid with their anticheat having previously worked for BattlEye and their solution it was by far the stupidest thing I've seen in a long time.

* Process Hacker doesn't in fact do anything special. It uses the Windows NativeAPI for everything so targeting Process Hacker won't stop other tools using the same functions. This is why forks of Process Hacker such as TaskExplorer (that uses our source) continued working even when they're targeting Process Hacker.

So now we're dealing with malicious software distributing Riot kernel drivers after they hard-coded our kernel driver because their staff were too lazy to reach out for a conversation and our competitors are laughing because their software has the same features but wasn't affected.

**Comment by DavidXanatos** [comment]
> 
> Text has copyright. Try copying html, javascript, LUA and other strings on your machine into a product and selling it for profit without licencing those works.
> 

I know but there are things like right to quotation, Threshold of originality and fair use etc....
I'm afraid if push comes to shove than the outcome is anything but certain if the work in question is a 25 character long string.

>
> ... because our certificate has expired and will take time and money to fix an issue created by their idiocy.
>

Oh... that is of cause a problem :/
I wonder if a smart lawyer could force them into sponsoring a new certificate ;)

> 
>  This will be added in a future version with some other features.
>
glad to here that :D

**Comment by DavidXanatos** [comment]
anyhow.... 

This certificate situation is a problem that must be more common, 
one should start some sort of foundation to sign drivers for open source projects,
for example ReactOS did that in the past but not anymore.

How much would that cost... IMHO whatever a LLC costs + 500-1000$/year for the cert itself.

**Comment by dmex** [comment]
> This certificate situation is a problem that must be more common

I've seen more a dozen developer tool projects on github now using leaked certificates like these:
https://github.com/hackedteam/GeoTrust

They've been revoked but the windows kernel doesn't have revocation checking so they're still working for signing/loading kernel drivers.

> glad to here that :D

The original issue was fixed in updates to riots driver so we can close this. The other issue with malware using their older versions is a newer separate issue which will be fixed at some point when we obtain a new certificate.

**Comment by dmex** [comment]
>  can be used in games for cheating

Process Hacker shows information about what your machine does in realtime and indirectly what Vanguard does in realtime, so being able to view information about Vanguard is considered cheating.

The main issue  people don't understand about blocking Process Hacker... Process Hacker at its core is a lightweight parser of data provided by the NativeAPI and everything Process Hacker does and shows was provided by that same API. The NativeAPI has been built-into every version of Windows (https://en.wikipedia.org/wiki/Native_API) since around 1990 and updated to the latest Win10.

You don't block the NativeAPI by blocking the Process Hacker binary... You can still call the NativeAPI functions and get the exact same information and preform the exact same operations using the exact same source-code from a different binary.

There are hundreds of applications and projects here on Github using the exact same NativeAPI and have identical functionality and features as Process Hacker. Even competitor products and projects that were forked from Process Hacker using identical code are unaffected. This might be an issue for closed-source projects because that requires the company/developer releasing updates but Process Hacker is open-source and anyone can download the source and recompile the binaries🤣

All Vanguard are currently doing is effectively blocking the official Process Hacker binary while ignoring everything else including binaries compiled from the same Process Hacker source-code.

My best guess is that Riot are blocking Process Hacker because they're idiots and don't know Windows internals? I previously worked at BattlEye and Process Hacker is not an exploit vector.

1) You will not get banned for using Process Hacker with BattlEye or with Easy Anti-Cheat.
2) BattlEye and Easy Anti-Cheat (EAC) don't force reboot your machine.

You should refund products that blame Process Hacker for cheating and always refund products that force reboot.

_Originally posted by @dmex in https://github.com/processhacker/processhacker/issues/725#issuecomment-719913385_
