### ISSUE TITLE
A very small QoL feature I'd like added (because I'm lazy)

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#642]
Just to use Notepad++ as an example, I really like how in their "about" menu have quick and easy links to their forums and GitHub, etc. for the lazy like me to who like to "check in" every once in a while to see the issues and discussions around releases, etc.

Could some more links be added to ProcessHacker's own about window, specifically this here place GitGub and maybe your (kinda dead but still lots of useful information) forums? :P

Notepad++
https://i.imgur.com/OhetypT.png

ProcessHacker
https://i.imgur.com/iX7gaRW.png

**Comment by dmex** [comment]
> specifically this here place GitGub

An issue recently was that since our binaries are hosted on Github and the terms of service prohibit using GitHub as a means to deliver malicious executables... Some individuals attempted to have our project removed from Github after some Microsoft employees publicly declared our project was malicious.

So for the moment I'm hesitant to include links to Github from release binaries just in case we're forced to relocate our source repository... There's already a link to our SourceForge project page and it includes links to our Github project so I would argue that's enough for now.
