### ISSUE TITLE
CPU time does not show days

### ISSUE THREAD

**Issue by Melirius** [processhacker/processhacker#644]
I have a program running for days long, so CPU time is large. However, Process Hacker does not show days anywhere (neither in the main window, nor in the process properties window) and show only (hours % 24), contrary e.g. to Process Explorer. I suggest to show days there or do not truncate hours. Also the cycles number is too long to fit into the field width, so it is also truncated.

**Comment by Melirius** [comment]
![Process Hacker](https://user-images.githubusercontent.com/47280527/87304028-d1553580-c51c-11ea-8625-e30403cb70c4.png)
![Process Explorer](https://user-images.githubusercontent.com/47280527/87304031-d1edcc00-c51c-11ea-8239-7a2f75b5b586.png)

**Comment by SanderBouwhuis** [comment]
Personally, I would prefer to keep it as hours instead of adding days. So, 26 hours instead of 1 days, 2 hours.
But, I do agree that this should work properly.

**Comment by dmex** [comment]
>  the cycles number is too long to fit into the field width, so it is also truncated.

This was fixed in the nightly builds about a year ago:
https://processhacker.sourceforge.io/nightly.php

> Process Hacker does not show days anywhere

This was fixed in the latest nightly build (about 10 minutes ago) :P

> I would prefer to keep it as hours instead of adding days. So, 26 hours instead of 1 days, 2 hours.

The value would reset back to 0 instead of showing 26 hours. This would be an issue so I've added the number of days to the latest nightly.
