### ISSUE TITLE
Every game warning

### ISSUE THREAD

**Issue by supertrio17** [processhacker/processhacker#646]
Hey, so I'm a big fan of Process Hacker, and I use it to replace Task Manager on every PC I have, but the thing is, on my gaming PC, every single game that has some sort of security, like scanning processes, detects it as a cheat, even when you close it, it still renders as a cheat, so I was wondering, is there any way to fix this?

**Comment by VictorVG** [comment]
It has been known for a long time. Not a bug, but a false message from the game about a non-existent threat.

**Comment by Syst3mSh0ck** [comment]
I believe the kernel driver and userspace would both need rewriting to avoid detection. It would be a time consuming process.

**Comment by Biswa96** [comment]
So, What bad things does ProcessHacker do that it needs rewriting?

**Comment by VictorVG** [comment]
It's not about the driver, and not about the PH architecture, but a letter from an employee of a corporation that creates games, written a few years ago, "_Process Hacker can possibly be used to hack our games, and therefore we demand to remove all its features from it!_".

And even after, at their request, the number of features of version 2.x that they indicated was removed from version 3.0, this corporation did not withdraw its claims, but on the contrary began to pay antivirus and other companies for adding PH to the lists of malware. and even if PH is rewritten again, it will not change anything, because for the owners of this company it is impossible to admit the groundlessness of their claims - the scandal will be too loud, and to buy everyone to be silent - even Uncle Sam will not print so many candy wrappers.:)

**Comment by dmex** [comment]
> every single game that has some sort of security, like scanning processes, detects it as a cheat, even when you close it

As someone who has spent the last decade working at two major game publishers and also worked in the anti-cheat industry....  You should immediately remove games your machine that are targeting Process Hacker.

> even when you close it, it still renders as a cheat, so I was wondering, is there any way to fix this?

You mistake the problem as technical instead of political/incompetence.

Process Hacker has been compatible with VAC, EAC and BattlEye since 2016 after we made technical changes allowing anti-cheats to use the ObRegisterCallbacks function to filter out handle permissions used by Process Hacker thereby disabling incompatible features.

ObRegisterCallbacks prevents Process Hacker - even our kernel driver -  from accessing threads, memory, modules, handles and literally everything else. 

There is nothing else we can do to make Process Hacker compatible with anti-cheat and that is why VAC, EAC and BattlEye (used across thousands of games) do not consider Process Hacker a cheat.

The companies that are continuing to target Process Hacker are either doing so because of incompetence or because they're highly likely to be doing something illegal which would be clearly identifiable using tools like Process Hacker (like GamersClub anticheat dropping malware on users machines) so are maliciously targeting the project to cover up this behaviour.
