### ISSUE TITLE
Process Hacker built from source, service notifications do not work

### ISSUE THREAD

**Issue by psisis** [processhacker/processhacker#647]
I have built the release branch 64-bit from source on Visual Studio 2019, also the plugins and even plugins-extra. I had installed a pre-built binary of Process Hacker 2 before and service notifications worked fine. But my own build does not work, I have enabled all notifications. Is there any debugging I can do myself? I appreciate the help.

```
Process Hacker
Version: 3.0
Compiled: 22:55:37 2020-07-11
```

**Comment by VictorVG** [comment]
@psisis

If I understand you correctly, then you want to see messages like service ... started / stopped? This is enabled in the Notification submenu (invoked by the right mouse button) of the mini tray window.

**Comment by dmex** [comment]
>  But my own build does not work

Do you have any visible tray icons?

**Comment by psisis** [comment]
@VictorVG 
Yes, that’s correct. The little window that pops up when services change. I have enabled all the options in the submenu. And in the actual program the Services tab is working.

@dmex 
Yes, it’s totally functional, I can right click on it -> Notifications -> Enable all. But it does nothing

**Comment by VictorVG** [comment]
Ok!

**Comment by dmex** [comment]
> I had installed a pre-built binary of Process Hacker 2 before and service notifications worked fine. But my own build does not work, 

The problem is the shell tray icon cache. The shell blocks two executables with different executable paths from using the same tray icon guids when calling Shell_NotifyIcon.

You need to either reset the tray icon cache or re-generate the tray icon guids in the settings file. The first option can be done by terminating explorer.exe and removing the cache keys from the registry.

The alternate method is removing this line from the Process Hacker settings file which will generate new guids:
`<setting name="IconGuids">{GUID}|{GUID}|{GUID}</setting>`
