### ISSUE TITLE
Misleading information on alternativeto

### ISSUE THREAD

**Issue by keeganwitt** [processhacker/processhacker#657]
https://alternativeto.net/software/process-hacker/ says Process Hackers is discontinued and may not be safe.  I don't believe either of these statements to be true.  I'm not sure if you can contact them as the developer to be able to update this (hello@alternativeto.net).  I didn't see an option to mark those flags as incorrect as a regular user of the site.

**Comment by Biswa96** [comment]
There is a little Settings like icon in upper right corner where you can report about it. That website marked it as malware based on VirusTotal results.

**Comment by Biswa96** [comment]
There is a little Settings like icon in upper right corner where you can report about the misinformation. That website marked ProcessHacker as malware based on VirusTotal results.

**Comment by dmex** [comment]
> says Process Hackers is discontinued

No, the project has not been discontinued.

They cite the last version as being released in 2016 but that version is the LTS (Long Term Support) release which supports Windows 10 and since Windows 10 is the last version of Windows so we're able to provide support for that version for years.

The downloads page did state this but I updated the entire site a few weeks ago and removed the (LTS) text thinking it wasn't needed.

> and may not be safe.

‘can’, ‘may’, ‘could’, 'might'... typical misleading garbage with uncited sources that's common these days.

> if you can contact them as the developer

You should be able to contact them and cite this post. As one of the project owners and lead developer I can state with a matter of fact that their information is incorrect.

**Comment by keeganwitt** [comment]
> There is a little Settings like icon in upper right corner where you can report about the misinformation. That website marked ProcessHacker as malware based on VirusTotal results.

I saw that, but didn't see what field to change for this.  Maybe it was just the label?  I see someone's got pending changes now.
