### ISSUE TITLE
Configure Dbghelp.dll path manually.

### ISSUE THREAD

**Issue by avielsh** [processhacker/processhacker#662]
Hi

On ProcessHacker 3.x there's no option to configure dbghelp.dll and it is not detected from the registry. 

On Pe 2.x there was an option to set the dbghelp.dll path..

Setting manually is also needed in case of using a portable version.

**PH**: 3.0.3263
**OS**:  Win7x64 7601
**Debugging tools**: Debugging Tools for Windows (x64) 6.12.2.633 - Installed on **C:\Program Files\Debugging Tools for Windows (x64)**

**Comment by dmex** [comment]
> ProcessHacker 3.x there's no option to configure dbghelp.dll and it is not detected from the registry.

The option to configure the path was removed since a anticheat product was modifying our settings file in their kernel driver filter callbacks and stripping those lines from the file to prevent Process Hacker loading symsrv and downloading symbols.

> it is not detected from the registry.

I removed the settings in favour of the registry detection. The KitsRoot10 key provided by the SDK specifies the dbghelp path:

![image](https://user-images.githubusercontent.com/1306177/90835178-3d824f00-e38f-11ea-9cf8-b1757cfb73b8.png)

The detection works fine on my test machines so if dbghelp is not being detected and the KitsRoot10 key is valid then a registry filter callback or some other software is blocking access to the registry key. It would also be affecting other software since Visual Studio, Windbg and other software also depend on those registry values.

> Setting manually is also needed in case of using a portable version.

If you're using a portable version then just copy these DLLs into the Process Hacker installation directory:

symsrv.dll
dbghelp.dll
dbgcore.dll

If the KitsRoot10 key doesn't exist then these files are loaded from the default search path including System32 and the current installation directory. Those three files are required because symsrv depends on dbghelp and dbghelp depends on dbgcore. If they don't exist then they can't be loaded.

**Comment by avielsh** [comment]
In my machine, KitsRoot10 was pointing to the x86 version - `C:\Program Files (x86)\Windows Kits\10\` which did not contain the debug dlls. I believe this key was modified from a VS2017 libraries install.
Installing afterwards the debugging tools for windows x64 did not modify the registry key (nor do I think it should have) which resulted in the debug dlls no getting detected.

Just a note, the windows 7 x64 debugging tools for windows do not include dbgcore.dll
Copying `symsrv.dll` and `dbghelp.dll ` into Process hacker's directory (on windows 7,) is enough to display the symbols..
Thanks

**Comment by dmex** [comment]
>  the windows 7 x64 debugging tools for windows do not include dbgcore.dll

dbgcore is only required for recent versions of Windows 10 👍🏿
