### ISSUE TITLE
Feature: Preventing detection

### ISSUE THREAD

**Issue by contrabyte** [processhacker/processhacker#665]
So certain malware will scan running processes for window titles containing 'Process Hacker', 'Process Explorer', 'Ghidra', 'API Monitor', etc. as well as process location/filenames and either kill the process or end themselves to prevent further snooping.

While it's probably unreasonable to expect ProcessHacker to be entirely undetectable, it would be nice if there was a "Reopen as stealth" option under the 'Hacker' menu that would cause process hacker to copy itself to %tmp%, renaming the main executable to something perhaps randomized, exit and open the "stealth" version with an argument that will blank out the title and the titles of any child windows. Which would at least exclude it from mass detection schemes that a lot of malware run every 5-10 ms.

**Comment by poizan42** [comment]
@contrabyte The problem here seems to be the plugin model of Process Hacker. The plugin api functions are exported from ProcessHacker.exe and linked to from plugin dlls. To fix this I think it would have to instead pass on a table of function pointers when initializing plugins and have the plugins call through that table, which seems like a lot of work to change.

**Comment by dmex** [comment]
> would be nice if there was a "Reopen as stealth" option

* The initialization code creates a detection method.
* Any stealth feature would be copy/pasted by people into other projects.

> that would cause process hacker to copy itself to %tmp%

%temp% generates false positives by antivirus checking for the %temp% path.

> renaming the main executable to something perhaps randomized

You can rename the executable using Explorer.

> blank out the title and the titles of any child windows

You need to change `EnableWindowText` setting to 0

> they will probably stick to those rudimentary string checks.

These detection methods only apply to the official builds but not derivatives based on the source code. If you added a detection method for a string you can download the source code and change or remove the string. 

The malicious software then needs an update to detect your modification. 

You can only write detection methods for the existing code published online and so you have to download the source and make the necessary changes. This is because when I publish source changes they'll just be copy/pasted so you need to create a local repository with your modifications.

> stupidity of antivirus programs.

The project has been open source for 12 years and can be reviewed on Github and Sourceforge.

>  when I rename the EXE to something else ... no longer load plugins

This was fixed in the nightly builds:
https://processhacker.sourceforge.io/nightly.php

> To fix this I think it would have to instead pass on a table of function pointers when initializing plugins and have the plugins call through that table, which seems like a lot of work to change.

You already have the import table without needing a second table.

> The plugin api functions are exported from ProcessHacker.exe and linked to from plugin dlls. 

You can change how the CRT handles imports using the __delayLoadHelper2 symbol:
https://docs.microsoft.com/en-us/cpp/build/reference/understanding-the-helper-function?view=vs-2019

**Comment by xprzemekw** [comment]
@contrabyte 

Issue with AV is that they try to be so clever that they mark any software which relates to process monitoring or debugging as *Potentially* unwanted software. Pay attention to *potentially* word. Home user ca  add exception, however security teams in corporations are often inhabited by idiots who can't analyse written words and treat this as a malware. (btw exception could be easily added because process hacker is digitally signed)

Same fate happened to https://github.com/icsharpcode/ILSpy project (.net debugger). It started being recognized as potentially unwanted.

**Comment by contrabyte** [comment]
First, thank you so much for looking into this issue. I agree that with open source projects it's trivial to see and counteract any methods of avoiding detection. The fix I detailed a few months earlier (changing `ProcessHacker.exe` to `processhacker.exe`), enabled me to document the malware's behavior and complete my research many months ago. Your fix in the nightly build version has enabled me to research a few other projects I had postponed, so thank you for that that as well. I agree that ultimately fighting with AV's and malware developers is a fruitless battle that is not worth fighting since detection methods will always be immediately visible given the nature of open source projects.

Still, I thank you for your time and effort. Merry Christmas, Happy new year and stay safe!

contrabyte

**Comment by dmex** [comment]
> I agree that with open source projects it's trivial to see and counteract any methods of avoiding detection.

There are methods available but the best and most reliable options are signature restricted by Microsoft and requests for those features were denied #454

> Your fix in the nightly build version has enabled me to research

If you come across others then feel free to email me about it (address is on my github profile). 

There's some techniques for avoiding malware detection which don't get published online and I can always compile custom builds of Process Hacker for those specific cases.

> I agree that ultimately fighting with AV's and malware developers is a fruitless battle that is not worth fighting since detection methods will always be immediately visible given the nature of open source projects.

It's been my experience that type of behaviour does major damage to them and their products over the long run. A product that blocks/targets other products simply frustrates end users to death with higher resource usage, stupid actions and other crap eventually losing those customers whom get tired of having to deal with it.

> Merry Christmas, Happy new year and stay safe!

Thanks! Merry Xmas and happy new year 🥳
