### ISSUE TITLE
Distinguish between "Apps" and other processes

### ISSUE THREAD

**Issue by FredWahl** [processhacker/processhacker#684]
The Windows Task Manager makes a distinction between "Apps" and other processes Firefox is an app as is Visual studio. I think that's neat. How this is done is a complete mystery to me, I would like to do this in my own code, written in C++. If Process hacker does in fact make this distinction,even if I can't see it, please tell me where in the code that distinction is made. Is there some function like IsAppsProcess() somewhere in the code? 

Best regards,
Fredrik

**Comment by dmex** [comment]
> How this is done is a complete mystery to me

A top level window is basically everything TM does to categorise processes on the 'Apps' tab minus a few more checks for AppUserModelId needed for grouping child processes.

'Apps' category is based on top level windows. It uses the `EnumWindows` API to enumerate top level windows and checks `IsWindowVisible(WindowHandle) && !GetParent(WindowHandle)`

If the process doesn't have any top-level windows then it's placed in the 'Background processes' category. The 'Windows processes' category is a hard-coded list of strings for system processes "System", "wininit.exe", "smss.exe", "svchost.exe"...

> If Process hacker does in fact make this distinction,even if I can't see it, please tell me where in the code that distinction is made. Is there some function like IsAppsProcess() somewhere in the code?

Process Hacker doesn't make that same distinction because you can search, filter and view processes based on more criteria than just the top level window.
