### ISSUE TITLE
Updater cache

### ISSUE THREAD

**Issue by anonymous1184** [processhacker/processhacker#687]
Updater leaves traces in %AppData%(\Process Hacker\Cache) even with a `ProcessHacker.exe.settings.xml` file next to the executable ("portable" mode).

Updater maybe should use the %Temp% folder?

**Comment by dmex** [comment]
> Updater leaves traces in %AppData%(\Process Hacker\Cache)

The updater deletes the cache directory using the PhClearCacheDirectory function after startup. 

Just like the system %temp% directory there's a timed delay before clearing the directory. If you cleared the cache too soon there would a race condition with a pending update being deleted before it can update when PH relaunches to install the update because the cache gets cleared after startup where the update gets installed from.

> settings.xml file next to the executable ("portable" mode).

This needs to be fixed 👍🏿 

> Updater maybe should use the %Temp% folder?

The path was changed to remove false positives by security products. Their 'heuristics' give processes higher scores for malicious when the executable location was from the %temp% directory. 

We already use that directory for applications settings and the geoip database. It's better to keep the updates and everything in one location and not share the same folders (%temp%) as other applications. It's also not a directory used by most software these days (probably for the same reason). For example chromium based applications and stores/launchers/games/updaters also use their own directories in %appdata% for temporary files and updates.

**Comment by dmex** [comment]
Fixed 👍
