### ISSUE TITLE
What is KProcessHacker

### ISSUE THREAD

**Issue by desbest** [processhacker/processhacker#706]
The installer asks me if I want to install KProcessHacker and that it's not recommended.
What is KProcessHacker?

**Comment by dmex** [comment]
> What is KProcessHacker?

The kernel driver.

> that it's not recommended.

It's not recommended because some games and programs scan for our driver and forcefully reboot your machine. There are also companies using it as an end-run around GDPR and keeping logs about users with the driver installed.

So it's not recommended for now.

> if I want to install KProcessHacker

The stable version always installs the kernel driver. That option is for allowing connections from processes without debug privileges such as when Process Hacker hasn't been elevated to administrator.

The nightly version recently started disabling the driver by default. The option is no longer available without administrator privileges.

I'd recommend using the nightly version since it has more features to avoid interference by third party software:
https://processhacker.sourceforge.io/nightly.php

**Comment by crjase** [comment]
Shame that we can't modify our own kernel without games making a fuss over it
