### ISSUE TITLE
ProcessUserShadowStackPolicy question earlier

### ISSUE THREAD

**Issue by ronsav80** [processhacker/processhacker#710]
thanks for reply to install SDK, but just FYI that ProcessUserShadowStackPolicy is introduced in Win10 version 2004 (which my dev machine isn't at yet)... 

https://docs.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-process_mitigation_policy
ProcessUserShadowStackPolicy | Windows 10, version 2004 and above: The policy regarding user-mode Hardware-enforced Stack Protection for the process.

**Comment by dmex** [comment]
> FYI that ProcessUserShadowStackPolicy is introduced in Win10 version 2004

I don't understand the issue?

**Comment by dmex** [comment]
> FYI that ProcessUserShadowStackPolicy is introduced in Win10 version 2004
> which my dev machine isn't at yet

The project supports all versions of Windows both for compilation and at runtime. You can install the Windows 10 SDKs on Windows 7 and compile the code... You just need the latest SDK version installed which is currently 19041 because some types are in that version which are not available in previous versions.
