### ISSUE TITLE
Add CTRL+C (copy) into about dialogue

### ISSUE THREAD

**Issue by MarekKnapek** [processhacker/processhacker#717]
It is difficult to report bugs if I need to retype Process Hacker version, it is tedious process and I could make mistake.

Please add CTRL+C (copy) keyboard shortcut into About dialogue so I can easily copy & pasta Process Hacker version into bug report or discussion forum.

Process Hacker version 3.0.3521.

**Comment by dmex** [comment]
> version into bug report

The Diagnostics button on the About dialog shows the version when you need a copy. The version isn't really important for bug reports since there are continuous builds/versions every day and sometimes multiple versions in one day.

It's mainly for checking the current version is todays version. For bug reports it's easier just to mention 'nightly builds'
