### ISSUE TITLE
Extra plugins not showed and don't work 

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#722]
Extra plugins not showed and don't work

**Comment by dmex** [comment]
`EnableSafeDefaultPlugins` must be zero for non-default plugins

**Comment by Avtroman** [comment]
> `EnableSafeDefaultPlugins` must be zero for non-default plugins

Ok, thanx!

**Comment by 0x4E69676874466F78** [comment]
*EnableDefaultSafePlugins

**Comment by dmex** [comment]
@0x4E69676874466F78 

The name changed when the plugin interface had breaking changes. Old plugins will crash newer versions of the program, so it's recommended you don't disable the safe plugins.

**Comment by 0x4E69676874466F78** [comment]
@dmex After minor edits, almost all extra-plugins work without problems for me.

**Comment by dmex** [comment]
@0x4E69676874466F78 

Yep, that's how it's supposed to work 😄 

The problem is when you're using older plugins and update to newer versions. PH/SI will try load the plugins on startup and immediately crash if there's an outdated plugin installed.

Renaming the setting force resets this option back to the default for everyone (disabled) so when they install the newer version it won't instantly crash. If you re-enable the option and immediately start crashing then you'll know there's an outdated plugin causing it and not the update 👍

**Comment by 0x4E69676874466F78** [comment]
@dmex now I understand.
