### ISSUE TITLE
Valorant rootkit dislikes PH

### ISSUE THREAD

**Issue by feraldruid22** [processhacker/processhacker#725]
I think others who play Valorant like me and use PH also noticed this that after starting PH any time Valorant cant be played anymore because Vanguard is not properly functioning and you need to restart the whole computer just because of this.

**Comment by dmex** [comment]
> Vanguard is not properly functioning and you need to restart the whole computer

Vanguard forces the reboot so like any malware you should uninstall and refund. BattlEye and EAC don't have the same issue so it's only an issue for Vanguard's users.

**Comment by Biswa96** [comment]
I am interested in how ProcessHacker like tools can be used in games for cheating 🤣

**Comment by dmex** [comment]
>  can be used in games for cheating

The reason given was [Data mining](https://en.wikipedia.org/wiki/Data_mining)

Process Hacker shows information about what your machine does in realtime and indirectly what Vanguard does in realtime, so being able to view information about Vanguard is considered cheating.

The main issue  people don't understand about blocking Process Hacker... Process Hacker at its core is a lightweight parser of data provided by the NativeAPI and everything Process Hacker does and shows was provided by that same API. The NativeAPI has been built-into every version of Windows (https://en.wikipedia.org/wiki/Native_API) since around 1990 and updated to the latest Win10.

You don't block the NativeAPI by blocking the Process Hacker binary... You can still call the NativeAPI functions and get the exact same information and preform the exact same operations using the exact same source-code from a different binary.

There are hundreds of applications and projects here on Github using the exact same NativeAPI and have identical functionality and features as Process Hacker. Even competitor products and projects that were forked from Process Hacker using identical code are unaffected. This might be an issue for closed-source projects because that requires the company/developer releasing updates but Process Hacker is open-source and anyone can download the source and recompile the binaries🤣

All Vanguard are currently doing is effectively blocking the official Process Hacker binary while ignoring everything else including binaries compiled from the same Process Hacker source-code.

My best guess is that Riot are blocking Process Hacker because they're idiots and don't know Windows internals? I previously worked at BattlEye and Process Hacker is not an exploit vector.

1) You will not get banned for using Process Hacker with BattlEye or with Easy Anti-Cheat.
2) BattlEye and Easy Anti-Cheat (EAC) don't force reboot your machine.

You should refund products that blame Process Hacker for cheating and always refund products that force reboot.
