### ISSUE TITLE
If the named pipe is waiting for a connection with ConnectNamedPipe, Process Hacker fails to show the Security tab or the handle

### ISSUE THREAD

**Issue by Farxial** [processhacker/processhacker#746]
### The problem:
If `ConnectNamedPipe` waiting on the synchronous pipe:
* 2.39.124 does not show the content of the Security tab of the handle
* 3.0.3672 does not even show ~the handle~ handle name in the process handle list; and it takes some time to load the handle list (see UPD 2020-12-06)

### My context:
1. The code part where I create pipes + "debug" part (*fixed), start from`ContinueWithThisProcess2()` (connect pipe) or `ContinueWithThisProcess1()` (create pipes) or `ContinueWithThisProcess()`:

```
#define DBG_USE_PRINTF 1
#define DBG_MESSAGEBOX 1

#if DBG_USE_PRINTF
	#define dbg_print(format) printf(format)
	#define dbg_printf(format, args...) printf(format, args)
#else
	#define dbg_print(format) 
	#define dbg_printf(format, args...) 
#endif

#if DBG_MESSAGEBOX
	#define dbg_mb(message, flags) MessageBox(0, message, 0, flags)
	#define dbg_mbW(message, flags) MessageBoxW(0, message, 0, flags)
#else
	#define dbg_mb(message, flags) 
	#define dbg_mbW(message, flags) 
#endif

#define ERROR_AT "Error at:\n"

void AssertNull(PVOID value, DWORD locId, LPCTSTR message);
void AssertTrue(PVOID value, DWORD locId, LPCTSTR message);
void SetTokenIntegrityLevel(HANDLE hToken, LPWSTR sSid);
DWORD ContinueWithThisProcess();
DWORD ContinueWithThisProcess1();
DWORD ContinueWithThisProcess2();
BOOL processRequest();

void AssertNull(PVOID value, DWORD locId, LPCTSTR message) {
	AssertTrue(!value, locId, message);
}

void AssertTrue(PVOID value, DWORD locId, LPCTSTR message) {
	if(!value) {
		dbg_printf("GetLastError() = %u\n", GetLastError());
		dbg_mb(message, MB_OK | MB_ICONERROR);
		ExitProcess((locId << 16) | GetLastError());
	}
}

void SetTokenIntegrityLevel(HANDLE hToken, LPWSTR sSid) {
	DWORD result;
	
	TOKEN_MANDATORY_LABEL tml = {NULL};
	tml.Label.Attributes = SE_GROUP_INTEGRITY;
	
	result = ConvertStringSidToSidW(sSid, &(tml.Label.Sid));
	AssertTrue(result, 330, ERROR_AT "ConvertStringSidToSidW(sSid, &(tml.Label.Sid))");
	
	result = SetTokenInformation(hToken, TokenIntegrityLevel, &tml, sizeof(TOKEN_MANDATORY_LABEL) + GetLengthSid(tml.Label.Sid));
	AssertTrue(result, 340, ERROR_AT "SetTokenInformation(hToken, TokenIntegrityLevel, &tml, sizeof(TOKEN_MANDATORY_LABEL) + GetLengthSid(tml.Label.Sid))");
	
	tml.Label.Sid = LocalFree(tml.Label.Sid);
	AssertNull(tml.Label.Sid, 350, ERROR_AT "LocalFree(tml.Label.Sid)");
}

DWORD ContinueWithThisProcess() {
	DWORD result;
	
	HANDLE token;
	
	result = OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY | TOKEN_ADJUST_DEFAULT, &token);
	AssertTrue(result, 360, ERROR_AT "OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY | TOKEN_ADJUST_DEFAULT, &token)");
	
	SetTokenIntegrityLevel(token, L"S-1-16-0");	// Untrusted
	
	result = CloseHandle(token);
	AssertTrue(result, 370, ERROR_AT "CloseHandle(token)" "\nIn ContinueWithThisProcess()");
	
	return ContinueWithThisProcess1();
}

#define IN_MSG_BUFFER 4096
#define OUT_MSG_BUFFER 4096
#define IN_MSG_SIZE 64
#define OUT_MSG_SIZE 64
HANDLE pipeIn;
HANDLE pipeOut;
static unsigned char in_buffer[IN_MSG_SIZE];
static unsigned char out_buffer[OUT_MSG_SIZE];

DWORD ContinueWithThisProcess1() {
	DWORD result;
	
	LPWSTR *argv;
	int argc;
	
	argv = CommandLineToArgvW(GetCommandLineW(), &argc);
	AssertTrue(argv, 500, ERROR_AT "CommandLineToArgvW(GetCommandLineW(), &argc)");
	
	if(argc < 3) {
		LocalFree(argv);
		return ERROR_BAD_ARGUMENTS;
	}
	
	pipeIn = CreateNamedPipeW(argv[1], PIPE_ACCESS_INBOUND | FILE_FLAG_FIRST_PIPE_INSTANCE, PIPE_TYPE_MESSAGE | PIPE_READMODE_MESSAGE | PIPE_WAIT | PIPE_REJECT_REMOTE_CLIENTS, 1, OUT_MSG_BUFFER, IN_MSG_BUFFER, NULL, NULL);
	AssertTrue(pipeIn != INVALID_HANDLE_VALUE, 510, ERROR_AT "CreateNamedPipeW(argv[1], ...)");
	pipeOut = CreateNamedPipeW(argv[2], PIPE_ACCESS_OUTBOUND | FILE_FLAG_FIRST_PIPE_INSTANCE, PIPE_TYPE_MESSAGE | PIPE_READMODE_MESSAGE | PIPE_WAIT | PIPE_REJECT_REMOTE_CLIENTS, 1, OUT_MSG_BUFFER, IN_MSG_BUFFER, NULL, NULL);
	AssertTrue(pipeOut != INVALID_HANDLE_VALUE, 520, ERROR_AT "CreateNamedPipeW(argv[2], ...)");
	
	argv = LocalFree(argv);
	AssertNull(argv, 530, ERROR_AT "LocalFree(argv)");
	
	return ContinueWithThisProcess2();
}

DWORD ContinueWithThisProcess2() {
	DWORD result;
	
	DWORD n;
	
	for(;;) {
		dbg_print("ConnectNamedPipe(pipeIn, NULL) :");
		result = ConnectNamedPipe(pipeIn, NULL);
		AssertTrue(result || GetLastError() == ERROR_PIPE_CONNECTED, 540, ERROR_AT "ConnectNamedPipe(pipeIn, NULL)");
		
		dbg_print("ReadFile(pipeIn, ...) :");
		result = ReadFile(pipeIn, &in_buffer, sizeof(in_buffer), &n, NULL);
		AssertTrue(result, 550, ERROR_AT "ReadFile(pipeIn, ...)");
		
		BOOL allowContinue = processRequest();
		if(!allowContinue) {
			break;
		}
		
		dbg_print("ConnectNamedPipe(pipeOut, NULL) :");
		result = ConnectNamedPipe(pipeOut, NULL);
		AssertTrue(result || GetLastError() == ERROR_PIPE_CONNECTED, 560, ERROR_AT "ConnectNamedPipe(pipeOut, NULL)");
		
		dbg_print("WriteFile(pipeOut, ...) :");
		result = WriteFile(pipeOut, &out_buffer, sizeof(out_buffer), &n, NULL);
		AssertTrue(result, 570, ERROR_AT "WriteFile(pipeOut, ...)");
	}
	
	DisconnectNamedPipe(pipeIn);
	DisconnectNamedPipe(pipeOut);
	// ...
	
	result = CloseHandle(pipeIn);
	AssertTrue(result, 580, ERROR_AT "CloseHandle(pipeIn)");
	
	result = CloseHandle(pipeOut);
	AssertTrue(result, 590, ERROR_AT "CloseHandle(pipeOut)");
	
	return 0;
}

BOOL processRequest() {
	if(in_buffer[0] != 0x55) {
		
		//doWork();
		return TRUE;
	} else {
		return FALSE;
	}
}
```
2. Pipes are for a child process, which is created with `CreateProcessAsUser` with a restricted token with all groups disabled except Integrity, Logon ID, BUILTIN\Users and Everyone, with Integrity=Low, and then level downs to Untrusted (the last part in the code snippet). **UPD:** All privileges (including `SeChangeNotifyPrivilege`) are also removed from the restricted token.
3. No pipe clients yet.
4. OS: Windows 7 SP1 x64. 3.0.3672 tested in VM.
5. Process Hacker runs as Administrator.

Sorry for the harm to your eyes by my code (my code is not ideal, I know; but it's just a draft) and for my bad English.

**UPD 2020-12-06:**
I added a delay before `ConnectToNamedPipe`, so now I can know the handle value. After reopening the process properties window, Process Hacker 3.0.3672 shows the handle, if "Hide unnamed handles" unchecked, but no Name.

**Comment by dmex** [comment]
> If ConnectNamedPipe waiting on the synchronous pipe:

This is a flaw with Windows that has existed for almost two decades.

NtQueryObject deadlocks usermode processes when they query the name of pipe and console handles because the handle is synchronous (meaning each call must complete before the next call continues) and the pipe is in a wait state. 

You have to duplicate the handle and query the name using NtQueryObject but the duplication also copies the wait state and synchronous mode and since the IRP has AccessMode == UserMode the kernel waits on the handle (It doesn't when using KernelMode for the IRP) and blocks the query from returning until the previous call completed (which it never does because the named pipe server is always in a wait state listening for clients) thus causing deadlocks in every user-mode process using NtQueryObject. 

I remember seeing in IDA years ago (Win2k or earlier) where NtQueryObject would check AccessMode == UserMode and instead call ZwQueryObject with KernelMode which was needed to fix the issue with NtQueryObject deadlocking usermode processes when querying the name but that code was removed in later versions of NT for some unknown reason and NtQueryObject has caused deadlocks ever since.


> 2.39.124 does not show the content of the Security tab of the handle
> 3.0.3672 does not even show the handle handle name in the process handle list

A kernel driver is required to query handle names properly. The kernel driver is enabled by default with v2 but disabled by default with v3 which is why you're seeing those differences.

> it takes some time to load the handle list 

When the kernel driver is disabled Process Hacker is forced to create a new thread for every call to NtQueryObject and terminate that thread after a timeout after the query deadlocks the thread:

1) Create thread
2) execute NtQueryObject
3) wait 1 second
4) terminate thread

This is the only solution to the deadlock issue with NtQueryObject when no kernel driver is available.... However when the kernel driver is available (enabled via the options window) we can simply:

1) execute ZwQueryObject

The kernel driver is a huge improvement to the reliability and performance of querying handle names. Just beware that a few game companies are keeping permanent records of anyone with the Process Hacker driver installed.
