### ISSUE TITLE
CPU frequency incorrect for AMD Ryzen 3xxx

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#765]
**Describe the bug**

the shown CPU Speed incorrect for AMD Ryzen 3xxx and likely also 5xxx

**To Reproduce**
1. Go to 'Systeminformation'
2. Look on 'CPU Speed' label and compare it to AMD Ryzenmaster

**Expected behavior**

Show same CPU frequency as AMD Ryzenmaster.

**Screenshots**

![AMDRyzen](https://user-images.githubusercontent.com/8274816/103339111-c9646000-4a80-11eb-85c6-05891e2a7ec2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1909

**Additional context**

AMD provides a [SDK for Ryzen Master](https://developer.amd.com/amd-ryzentm-master-monitoring-sdk/). So if the users have AMD Ryzen (>Zen2) and Ryzenmaster driver installed, use the driver to query the CPU data.

But also Windows itself fails to read if correctly, Taskmanager and ETW also report over 3GHz all time.

**Comment by dmex** [comment]
> Windows itself fails to read if correctly, Taskmanager and ETW also report over 3GHz all time.

I've used Ryzen Master before and it has always reported the wrong speed. Either way these values come from the hardware and there isn't anything we can do and AMD needs to fix their implementation.

**Comment by ge0rdi** [comment]
[HWiNFO](https://www.hwinfo.com/) author describes this difference in core clocks nicely in this article:
[Effective clock vs instant (discrete) clock](https://www.hwinfo.com/forum/threads/effective-clock-vs-instant-discrete-clock.5958/).

**Comment by MagicAndre1981** [comment]
> [Effective clock vs instant (discrete) clock](https://www.hwinfo.com/forum/threads/effective-clock-vs-instant-discrete-clock.5958/).

ok, this was helpful.

**Comment by dmex** [comment]
> HWiNFO author describes this difference in core clocks nicely in this article:

There is a reason why Windows doesn't do this and it's probably because it's incorrect and not accurate

**Comment by ge0rdi** [comment]
> There is a reason why Windows doesn't do this and it's probably because it's incorrect and not accurate

The article explains why _old_ method that uses P-states multipliers doesn't describe modern CPUs accurately.
I'd say HWiNFO author knows this better as the HWiNFO is really established and he is doing this kind of stuff for years.

Also Ryzen Master software directly from CPU vendor is expected to show proper information.
I'd say that Windows just didn't catch up with latest CPU technologies (or maybe doesn't care about actual effective CPU frequency that much).

That's said I don't think Process Hacker needs to do anything in this regard. It should use whatever data Windows reports.
There are specialized programs (such as HWiNFO) that can show more internal CPU details.

**Comment by dmex** [comment]
@ge0rdi 

> old method that uses P-states multipliers doesn't describe modern CPUs accurately.

I've been reading up on this some more and asked a few people... these methods work perfectly fine on Intel processors and older AMD processors. The blog post from hwinfo essentially says the same thing as other sources:

`"RM (Ryzen Master) uses a different (proprietary) technique to measure clocks"`
`"the current effective clock method is an architectural feature meaning that it doesn't depend on a certain CPU model"`


What has happened here is the result of AMD screwing with their architecture errata to prevernt software from properly comparing their chips against Intel processors without using their 'propriety' extensions which is why AMD created a proprietary method (that isn't documented in any of their errata) for determining the clock to prevent datamining/comparisons.

That's what's actually caused the "old method" to become inaccurate because AMD report inaccurate values unless you use their propriety extensions and also very likely why Microsoft refused to change anything on Windows. The alternative is that Microsoft are deliberately under/over reporting the clocks of AMD processors and favouring Intel which is doubtful because of lawsuits for doing that.

AMD should be up in arms about Windows reporting inaccurate clocks for their processors but they don't seem to care which leads me to believe its intentional on their part.

**Comment by ge0rdi** [comment]
I'd not say that anybody _screwed_ up here.
CPUs nowadays are just far more complex than they used to be.

Ryzen Master is simply trying to take that into account. And provide more precise look at how CPU operates.
See [here](https://www.reddit.com/r/Amd/comments/cjcrv2/how_can_ryzen_master_show_clocks_up_and_down/evd8tqs/?context=3).

**Comment by dmex** [comment]
@ge0rdi 

That post just described core parking in everything but name?

I was using an outdated manual and was wrong about the errata:
https://i.imgur.com/tVIhfhF.png
https://i.imgur.com/VKuFoDz.png

A related issue was fixed in more recent processors:
https://i.imgur.com/36C9tPU.png


If you have Ryzen Master installed or HWiNFO installed which is already querying the value then nobody else can query the effective clock without overwriting the registers and returning inaccurate results.

We would have to connect to the \device\AMDRyzenMasterDriverV16 device by loading/checking AMDRyzenMasterDriver.sys and using these structures:

![image](https://user-images.githubusercontent.com/1306177/103498471-03769d00-4e99-11eb-9b42-860148f13f3e.png)


The only problem with their driver is that it BSODs when HVCI/WSL2 (hypervisors) are enabled:

![image](https://user-images.githubusercontent.com/1306177/103498545-43d61b00-4e99-11eb-8c01-a3891014a172.png)


I'm not sure if we can support this in it's current state?

**Comment by ge0rdi** [comment]
> I'm not sure if we can support this in it's current state?

Imo there is no need for that.

PH should use standard Windows means for obtaining the current CPU frequency.
It is just informational value. I think more important value is actual CPU load.

If one needs more proper view on CPU state, he can always use specialized tools (RM / HWiNFO/ etc).

**Comment by MagicAndre1981** [comment]
> 
> The only problem with their driver is that it BSODs when HVCI/WSL2 (hypervisors) are enabled:
> 
> ![image](https://user-images.githubusercontent.com/1306177/103498545-43d61b00-4e99-11eb-8c01-a3891014a172.png)
> 

ok, I don't use WSL, so I haven't noticed that RyzenMaster bugchecks the device.
