### ISSUE TITLE
add a show graph per disk

### ISSUE THREAD

**Issue by monkeyoogabooga** [processhacker/processhacker#779]
what the title says, if task manager does it by default why doesnt process hacker
![image](https://user-images.githubusercontent.com/77422137/104534246-e7ce6d80-55e1-11eb-8d64-c65d22facefd.png)
![image](https://user-images.githubusercontent.com/77422137/104534309-0a608680-55e2-11eb-9f94-e7a59a1154db.png)

**Comment by dmex** [comment]
> if task manager does it by default why doesnt process hacker

You need to select the disks from the Options window > Disk devices:

![image](https://user-images.githubusercontent.com/1306177/104534652-c5336780-5668-11eb-8478-a8ada9a9d65a.png)

It's not automatic because not everyone wants to monitor disks and not monitoring everything by default improves performance.
