### ISSUE TITLE
Ver3.0 cannnot show the Object Address for the Handles

### ISSUE THREAD

**Issue by AgigoNoTana** [processhacker/processhacker#788]
ver2.39 could show the object address in [Handle Property -> General] tab, but, it cannot be shown in the ver3.0.
I attach the comparison screenshot.
![スクリーンショット 2021-02-03 19 18 14](https://user-images.githubusercontent.com/43233361/106830835-313a4600-66d2-11eb-86ba-f2350cd9b587.png)

**Comment by dmex** [comment]
This is by design. Windows 8 and above include a new feature called handle snapshots which give major performance improvements for handle enumeration with one limitation that does not provide the object address.

You'll need to do one of the following:
* Enable the kernel driver from the Options > General > 'Enable kernel-mode driver' checkbox and run PH as administrator.
or 
* Disable the handle snapshot feature by changing the `EnableHandleSnapshot` setting from 1 to 0
