### ISSUE TITLE
RAM usage does not match up with acttual RAM ussage

### ISSUE THREAD

**Issue by RedstoneMedia** [processhacker/processhacker#808]
**Describe the bug**
Absolute ram usage does not match up with acttual ram usage and displays more ram used than actually installed.

**To Reproduce**
1. Go to System information
2. See error on the left side under the text "Memory"

**Expected behaviour**
The used ram displays the amount of used physical RAM and not more then installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/34373974/108625567-eba8a780-744b-11eb-82ae-1c5524598f44.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Home 2004

**Additional context**
I have 8 GB of ram installed.

**Comment by dmex** [comment]
> Absolute ram usage does not match up with acttual ram usage and displays more ram used than actually installed.

PH by default shows the total commit memory and not the physical memory. If you're nearing the total commit maximum then you're going to have a very bad time on Windows compared to when you're nearing the total physical maximum.

If you would prefer to to use the total physical memory for those graphs then disable the "Show commit change instead of physical memory" option:
![image](https://user-images.githubusercontent.com/1306177/108626708-afa23080-74a5-11eb-9b85-94bcc9330e72.png)
