### ISSUE TITLE
Error 0xC0000005 after update

### ISSUE THREAD

**Issue by walterm128** [processhacker/processhacker#809]
**Describe the bug**
Error 0xC0000005 after update

**To Reproduce**
1. When Run ProcessHacker.exe

**Expected behavior**
Run ProcessHacker.exe

**Screenshots**
![Error](https://user-images.githubusercontent.com/47644901/108648044-f63d5e00-7498-11eb-9d89-7730ba3f8ebc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2 19042.508

**Additional context**
ProcessHacker.exe run with all plugin is disable (rename the folder)

Minidump
[ProcessHacker_JAPXPBCIRUZOUHX_DumpFile.zip](https://github.com/processhacker/processhacker/files/6019121/ProcessHacker_JAPXPBCIRUZOUHX_DumpFile.zip)

**Comment by dmex** [comment]
I've disabled a workaround that might be causing the crash, you'll need to re-download the latest nightly:
https://processhacker.sourceforge.io/nightly.php

Let me know if the crashes continue. I'm not sure what the crash could be since it's inside the internal Microsoft C Runtime (CRT) and not our code:

![image](https://user-images.githubusercontent.com/1306177/108664197-5cbc8d80-7526-11eb-8282-347701876e90.png)
