### ISSUE TITLE
Can't shrink main window vertically enough to show only 1 process item

### ISSUE THREAD

**Issue by altimumdelta** [processhacker/processhacker#818]
Hi

Most such utilities can shrink themselfs vertically enough so it hides most processes away leaving only 1 process at the top of the sorting method visible.

Curently the main window can only be shrinked to some limit that still shows around 10 processes, sometimes I use Always-on-Top to overlay PH over other things and would like PH to take as less space as possible.

I'm not entirely sure right now if this worked in the past, my memory says yes, but that could have been a different utility.

Thanks

**Comment by dmex** [comment]
The minimum size (since around 2008) has always been 400 pixels wide and 340 pixels high. This might have been more of an issue back then when the maximum screen sizes were 1024x768 but these days...

I can shave the minimum height down to 175 pixels but not more since it'll cause overlap/rendering issues... Is it necessary?

**Comment by dmex** [comment]
Changed minimum height to 175px in latest nightly?

**Comment by altimumdelta** [comment]
Yep, works great.
