### ISSUE TITLE
System unstable after Process Hacker update - Bad Image error

### ISSUE THREAD

**Issue by redactedscribe** [processhacker/processhacker#822]
**Describe the bug**
After logging on, I was presented with a popup to update Process Hacker's nightly version. This doesn't normally happen so I'm not sure why it did so this time. I updated, and since then my system has been experiencing instability.

Upon running Process Hacker, it'll complain about a `.dll`, two of them in fact, and I'm not sure why, could be random, but both say the same error (not 100% sure if they share the same error code), e.g.:

```plain
---------------------------
ProcessHacker.exe - Bad Image
---------------------------
C:\Program Files\GPSoftware\Directory Opus\dopuslib.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000428. 
---------------------------
OK   
---------------------------
```

When I click external links in Process Hacker, the same `Bad Image` error pop-ups appear, for example clicking Help > About > and then the linked commit number c9ef01c. I must've clicked the link a couple times successively because after that, every few minutes another tab of the same GitHub commit link would open. Opening and using applications are abnormally delayed on the system (Firefox and Discord so far), and VS Code ended up having a leak for whatever reason (something not happened before, and that I assume is related) and other programs started crashing because of limited memory.

Unfortunately, I'm not sure which nightly commit I came from as I didn't think to note it down before updating, but it's at least a month or two old.

How can I downgrade to an earlier nightly without having to build it myself?

There is also _no_ way to uninstall the program: it doesn't appear in the normal list of Windows apps to uninstall. I was hoping I could just uninstall and regain system stability, but apparently not. Perhaps just having it not run on boot will be enough.

**Update:** After disabling Process Hacker from running on boot (it was set to do so via a Task Schedule), the system was still unstable. Whether or not that rules out Process Hacker I'm not sure. My PC did also update to a Windows Preview update today, as well as installing a newer beta of Directory Opus (which in mentioned in the error above), so something else may be to blame. I don't think it is Directory Opus however as the other app Process Hacker produces the error about is a program I've not touched in many months. I have regained system stability, but this is after entering Safe Mode and deleting the Process Hacker program files, and uninstalling Directory Opus from the system. It's between Windows' update and Process Hacker's update I believe, but I'll do some more testing to try and find an answer, in case it involves Process Hacker.

**Update 2:** After reinstalling Directory Opus (beta released today), and a couple reboots, there seems to be no issue. That points to the absence of Process Hacker being the one potentially at fault (or an incompatibility with the latest Windows Preview). I do not have the time to test (re-install) Process Hacker, but maybe this account is enough to provide a lead. I'll be reinstalling your software in some weeks if there is no response, and seeing if anything has improved. Thanks.

 - OS: Windows 10 v20H2 (OS Build 19042.884)

**Comment by dmex** [comment]
> running Process Hacker, it'll complain about a .dll, two of them in fact

Those programs attempted to inject two DLLs into Process Hacker which are incompatible with the Microsoft signed only mitigation policy you've enabled by selecting the "enable mitigation policy" option in the settings window:

![image](https://user-images.githubusercontent.com/1306177/110227533-752c9f00-7f4d-11eb-8f93-9f15853f9d09.png)

>  Opening and using applications are abnormally delayed on the system (Firefox and Discord so far), and VS Code ended up having a leak for whatever reason (something not happened before, and that I assume is related) and other programs started crashing because of limited memory.

The mitigation policy is only applicable to the ProcessHacker.exe binary. Those same DLLs would have be injected into everything you're running on your machine so if you're having those sorts of stability issues then you should uninstall those programs that are injecting DLLs because they're hijacking/hooking/patching code.

Microsoft also broke some of the mitigation polices allowing software to silently bypass those polices and inject DLLs and other code despite those polices supposedly preventing the injection which is now being exploited by third party software to inject code: #641 

> How can I downgrade to an earlier nightly without having to build it myself?

You can download older nighties from Appveyor:
https://ci.appveyor.com/project/processhacker/processhacker/history

There's so much software using injection that I've re-disabled those "Bad image" error dialogs from Process Hacker when something failed to load in newer nightly builds so I don't recommend using older revisions: https://github.com/processhacker/processhacker/commit/8a048ec3d686e3a708e844d840f2a26cdacad306

> There is also no way to uninstall the program: it doesn't appear in the normal list of Windows apps to uninstall. 

The uninstaller is always created. There are no exceptions.

Windows Defender however deleted the uninstaller keys at least 40 times in the last 12 months under the guise of "false positives" which is likely why it's missing on your machine: #454

> After reinstalling Directory Opus (beta released today), and a couple reboots, there seems to be no issue. That points to the absence of Process Hacker being the one potentially at fault (or an incompatibility with the latest Windows Preview)

Process Hacker doesn't inject code or DLLs. The only thing that changed was enabling extra error messages in Process Hacker but they've been disabled again because the amount of software using faulty injection causes too much error dialog spam.

You'll find that those programs you mentioned have always been injecting code and failing but were not showing an error dialog because notifications for those types of errors were never visible. I've disabled the notifications again so you won't see those error dialogs when using Process Hacker but those programs will still be injecting code. So again, if you're having stability issues then you should uninstall those programs that are injecting DLLs into everything because that's not at all reliable or stable.

**Comment by redactedscribe** [comment]
> Those programs attempted to inject two DLLs into Process Hacker which are incompatible with the Microsoft signed only mitigation policy you've enabled by selecting the "enable mitigation policy" option in the settings window:

Thanks for pointing this out, however I don't recall ever enabling this as I did not know what it even does. Perhaps it was by mistake.

> The mitigation policy is only applicable to the ProcessHacker.exe binary. Those same DLLs would have be injected into everything you're running on your machine so if you're having those sorts of stability issues then you should uninstall those programs that are injecting DLLs because they're hijacking/hooking/patching code.

If Process Hacker was not at fault, then it would have to be that it has incompatibilities with Windows' Preview update or the softwares injecting code (most likely). My reasoning is: the only change I made was to reinstall Directory Opus (same version as previously), and uninstall PH. Essentially, the system is the same, only PH is removed. Peculiarly, I saw no high use of memory or CPU during these sustained slow-downs.

> The uninstaller is always created. There are no exceptions

For whatever reason, an uninstaller was not visible in CCleaner or Windows' Add or remove programs. Since I couldn't find the uninstaller, I booted into safe mode (as normal mode was unusable) and deleted everything in PH's installation directory, and then rebooted again. I was worried remnants were left over in other locations as normal mode still acting up, and so I installed the nightly again, which created an uninstaller, then used it to hopefully do a clean uninstall. Since then, things have been fine.

> Process Hacker doesn't inject code or DLLs. The only thing that changed was enabling extra error messages in Process Hacker but they've been disabled again because the amount of software using faulty injection causes too much error dialog spam.

Since you've disabled the "Bad Image" error, I will give the software another try.

> So again, if you're having stability issues then you should uninstall those programs that are injecting DLLs into everything because that's not at all reliable or stable.

If the problem return, I'll try to inform the authors of the programs that were causing the "Bad Image" error. However since I'm not well-versed in such topics, I can only point to this post. Hopefully that'll be enough of a lead.

Thank you for you help.

**Comment by redactedscribe** [comment]
> Those programs attempted to inject two DLLs into Process Hacker which are incompatible with the Microsoft signed only mitigation policy you've enabled by selecting the "enable mitigation policy" option in the settings window:

I've just reinstalled Process Hacker and moved my `settings.xml` back to `%appdata%\Process Hacker`. Checking the options shows that "Enable mitigation policy" is/was disabled.

**Comment by dmex** [comment]
> I was worried remnants were left over in other locations as normal mode was still acting up, and so I reinstalled the PH nightly which created an uninstaller, then used it to hopefully do a clean uninstall. Since then, things have been fine.

There's no difference between the setup and the portable build. The setup just extracts a 1:1 copy of the .zip onto disk (the same if you had used the portable.bin.zip) but it does create a registry key in the uninstaller hive so you can uninstall. The uninstaller just deletes the directory and removes the 'uninstall' key.

I wrote the installer from scratch with the exact intention of having no difference between the bin.zip and setup.exe just so everything gets removed unlike other software.

>  the "Bad Image" error dialogs should have been disabled in the build I was using (newer than 8a048ec), but they were still appearing. Maybe this is down to the "enable mitigation policy" option you mentioned that I can uncheck.

They should be disabled entirely. You can check if they should be disabled by adding the "Error mode" column to the processes list and checking if processhacker.exe has the following value:

![image](https://user-images.githubusercontent.com/1306177/111353313-49da4a80-86d9-11eb-82b0-b965e23619a6.png)

> I'll try to inform the authors of the programs that were causing the "Bad Image" error.

It's not their fault so much as that we're using a higher level of process mitigations than other software the same as Chrome/Edge have been using so their images should always fail the "Microsoft signed only" checks. There isn't much they can do about it without violating the mitigation policy.

They're supposed to fail but you're not supposed to get an error dialog when they fail. If you get another prompt then let me know 👍

**Comment by redactedscribe** [comment]
Just wanted to update that I believe the fault laid with Malwarebytes' Antivirus software playing up, not ProcessHacker. It was just a number of coincidences that lead me to believe PH was at fault. Thanks for the help.
