### ISSUE TITLE
REQ: Option to display per process CPU usage as % per core

### ISSUE THREAD

**Issue by bobpaul** [processhacker/processhacker#831]
On POSIX systems, process CPU usage is reported as 0-100% per core in a system. So if you have a 4 core system with hyperthreading, it might show up to 800% CPU. This has always made a lot more sense to me. I can look at a process and see it's using 70-125% CPU and I know it's bogging down a full core.

But when I work on Windows systems, I open up various reporting tools (Process Hacker, Process Explorer, Window's Task Manager) a process shows as 100% only if it's using all cores in the system. And this means I have to know how many cores are on a system before I know if 12.5% CPU usage is "high" or if it's basically an idle process. On some systems 5% CPU usage might be a full core. On other systems 50% CPU usage might be a full core. Often a good way to determine that a thread is "misbehaving" and stuck in some busy loop, is to observe that it's consuming an entire core.

Is it possible to provide this option?

**Comment by dmex** [comment]
You can add the "CPU (relative" column to the processes list and threads list for showing core relative utilization 👍

**Comment by bobpaul** [comment]
@dmex I don't see that option. I'm currently using v2.39.124

**Steps**
1. On the main process list ("Processes" tab), right click the column headers and choose "Choose Columns..."
2. Look for "CPU (Relative)" in the Inactive columns
3. Notice that's not an option.

Do I need to turn another option on, first? I have available columns `CPU History`, `Kernel CPU Time`, `User CPU time`, `Total CPU time`, but none of these sound like the right thing and the only option with ("Rel" in the name is "Relative Start Time").

**Comment by dmex** [comment]
> I'm currently using v2.39.124

You need to install the v3.0 build:
https://processhacker.sourceforge.io/nightly.php

**Comment by mesvam** [comment]
I have found "CPU (Relative)" a very useful column, but would you consider adding this as an option that applies across the entire program? Meaning anywhere CPU usage is shown (System Information graphs, tray icons & popup window, program graphs, etc.) it would be relative to a single core rather than system-wide.

As CPUs are getting more and more cores, I've also found this method of describing CPU usage much more intuitively useful. e.g. in a 16 core system, fully saturating one core would only show as 6.25% The number is just too small to intuitively understand. 6% just feels quite low, but it's actually a heavy load for a single threaded application. And a difference of 50% to 100% is much more intelligible than 3.125% to 6.25%, which looks like it barely changed.

**Comment by Fedottt-Bo** [comment]
I'd also wish such a feature was properly implemented, since even though there is a "relative" column for total CPU usage, there are no such for user/kernel usage, as well for "System Information" window, toolbar CPU history and etc. In fact, having only single column use relative scaling is really confusing, considering it's displayed along normalized ones.

**Comment by mesvam** [comment]
I split this out as a separate feature request https://github.com/winsiderss/systeminformer/issues/3034
