### ISSUE TITLE
"Enable tray information window" option not present v 2.39.124 on win 10 19042.

### ISSUE THREAD

**Issue by pbpb** [processhacker/processhacker#834]
**Describe the bug**
The bug/feature that was supposedly fixed in build of 1/15/17 apparently has regressed, as this option is not present for me.

Came up at:  https://wj32.org/processhacker/forums/viewtopic.php?t=2523

Post Title: "tray icon mouse hover preview: disable option"

**To Reproduce**
hacker > options does not have that option under any tab.

**Expected behavior**
It should be there.

**Desktop (please complete the following information):**

 win 10 19042.

**Additional context**
Toggling the value of the MiniInfoWindowEnabled item in the *settings.xml does work; but since I have portable version installed, it is not in the location noted in the post.

**Comment by dmex** [comment]
The option is still there?

![image](https://user-images.githubusercontent.com/1306177/111243491-4a310200-8655-11eb-9afe-41e3068e4516.png)

**Comment by pbpb** [comment]
Not there for me.  Where am I supposed to see that option?

**Comment by dmex** [comment]
2.39 has the `MiniInfoWindowEnabled` setting which you have to manually enable by manually changing the settings file.

The checkbox option on the general settings tab is available only in the nightly builds:
https://processhacker.sourceforge.io/nightly.php

**Comment by pbpb** [comment]
Aha, ok, thanks.  I assumed that if it was in the nightly builds in 2017, it might by now have made it to a release version.
Do you plan to put into a release version?  If I wanted it, maybe many others would like it, too.  Or is there some particular reason why it's not included in release?

**Comment by dmex** [comment]
> Or is there some particular reason why it's not included in release?

Microsoft created a new policy called "attestation signing" then banned my account from signing binaries/drivers. So I haven't been able to sign the executables and without the signing we can't release a new "stable" build since the updater requires signed binaries #454

**Comment by pbpb** [comment]
Aha.  Very annoying.  So, assuming I can successfully get a nightly build to 
run, how do I know which ones are stable enough that they would have been 
release candidates?

--peter

**Comment by dmex** [comment]
> how do I know which ones are stable enough

They're generally stable. If there's an issue with a nightly build then it's removed to prevent anyone using it until a newer build is pushed. You'll only get prompted for an update once every 7 days and we're running nightly myself. So issues are resolved and newer builds released before anyone runs into issues. Some issues do slip through but that's why bigger changes also go through more local testing before being released so there isn't generally issues with updating nightly builds.

Process Hacker does not ever make changes to your machine. So any issues are restricted to what/how things are visualized and displayed. There are zero risks of causing damage with the nightly builds. At worst PH just crashes and doesn't execute.

If you find an issue or don't like something and report it, we can fix the problem and release new build either within a few hours which is a better experience overall than what you'd get with other projects 👍

**Comment by midaspt** [comment]
So sorry for necro-posting but I've been having this issue in the latest nightlies builds -- also I cannot apparently close it to tray. Any advice welcome.

![](https://i.postimg.cc/1tPtFJsS/PH-about.png) ![](https://i.postimg.cc/nzkLGBhD/winver.png)

**Comment by midaspt** [comment]
I was able to solve the tray icon issue with the solution at #572, but I still can set PH (x64) to close to tray...
