### ISSUE TITLE
DPS memory re-write

### ISSUE THREAD

**Issue by buzziest** [processhacker/processhacker#855]
Hello I have one question. How do I UNDO a re-written memory in process hacker?
![image](https://user-images.githubusercontent.com/81512462/112749485-a77d6980-8fec-11eb-89db-e56f862321fb.png)
Here for example I edited the memory of the process (DPS) by replacing the those memories with 0
So i wanted to ask how do I undo that action? Or does that action leave any traces in process hacker that I should know to find if someone did that?

**Comment by dmex** [comment]
> how do I undo that action?

LmHex to open the file on disk and re-read the bytes for the offset:
https://github.com/WerWolv/ImHex

Alternatively since all those changes are not permanent, just reboot the machine. 

> Or does that action leave any traces in process hacker that I should know to find if someone did that?

The primary issue with undo is that it would require saving copies of every page for every character change which would very quickly use GB's of memory.
