### ISSUE TITLE
Links from About window and Donate item start iexplore with ProcessHacker privileges.

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [processhacker/processhacker#864]
**Describe the bug**
Links from About window and Donate item start iexplore with ProcessHacker privileges (Elevation: Full, Integrity: High).

**To Reproduce**
Help->Donate
Help->About->Click any link

**Expected behavior**
Start iexplore unprivileged (Elevation: Limited, Integrity: Medium).

**Screenshots**
![ph](https://user-images.githubusercontent.com/4449851/113703564-a979b380-96e3-11eb-93c4-bcb228ac531b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.1, 9600

**Comment by dmex** [comment]
There isn't any programmatic interface on Windows for querying the default browser. URLs are passed to the ShellExecuteEx function (the same way all other Windows software does) which launches your default browser which in your case is currently Internet Explorer and you shouldn't be using it as your default.

> Start iexplore unprivileged

This would be ideal but won't actually work because of how browsers handle their IPC with sandboxing and single instances… If another application on your machine called ShellExecute launching the browser with higher elevation integrity and then we attempted to launch another browser as medium integrity then our instance/requests would fail to launch the browser because it's already running with high integrity.

If you're already using Chrome/MsEdge and it's currently running as medium integrity and Process Hacker is running at high integrity then the URLs are correctly forwarded to the medium integrity browser processes so it's only an issue with legacy Internet Explorer.

**Comment by 0x4E69676874466F78** [comment]
@dmex Thanks for the detailed answer.
