### ISSUE TITLE
Cannot edit the proprieties/service settings of (MsMpEng.exe/Windows defender) with administrator permission 

### ISSUE THREAD

**Issue by LordOfNightmares** [processhacker/processhacker#870]
**Describe the bug**
Cannot edit the proprieties/service settings of `MsMpEng.exe` aka `Windows defender` even with administrator permission run.

**To Reproduce**

1. open `processhacker` with administrator perms
2. services tab
3. search def
4. select `WinDefend` service proprieties 
5. cannot change anything

**Expected behavior**
Should be able to change the service settings (_cough*_ process**hacker**)

**Screenshot**
![image](https://user-images.githubusercontent.com/24809075/115024904-611f7a00-9ec9-11eb-8cc9-4cb579de9b86.png)

**Comment by dmex** [comment]
> edit the proprieties/service settings of MsMpEng.exe aka Windows defender even with administrator permission

Administrators are restricted from making these changes to those services?

![image](https://user-images.githubusercontent.com/1306177/115428609-e8604b00-a245-11eb-84bf-422f262711d6.png)

> Should be able to change the service settings 

This is working as designed. You need to disable ELAM via bcdedit, reboot and disable tamper protection before changing those services.

> (cough* processhacker)

You're confusing this project with some type of exploitation framework... The name _Process Hacker_ is derived from the significant amount of reverse engineering aka _hacking_ required to implement Task Manager software for _processes_ on Windows since Microsoft doesn't document anything required for third party task managers while also actively preventing any competition with their task manager products. 

You should instead install Kali linux from the Windows Store since they have thousands of modules designed for exploitation of CVEs designed for attacking Windows and security products like Defender:
https://www.microsoft.com/en-us/p/kali-linux/9pkr34tncv07
