### ISSUE TITLE
FEAT/BUG: VirusTotal info if missing/differ after "Send to VT" action

### ISSUE THREAD

**Issue by Progress1** [processhacker/processhacker#872]
**Feature:** if for some reason is VirusTotal info missing and user manually do "Sent to VT" take this new value and update empty column. You can update it always (if is something changed e.g ratio..)

![image](https://user-images.githubusercontent.com/10151485/115348686-39732f00-a1b3-11eb-83ea-d69e1fd5cd50.png)

**Comment by Progress1** [comment]
When i restart PH i find interesting thing:
Column value differ from the report dialog value..

![image](https://user-images.githubusercontent.com/10151485/115350107-f74aed00-a1b4-11eb-8bf6-b01c108ee0af.png)

**Comment by dmex** [comment]
VirusTotal has been reporting incorrect details for months... I've tried emailing them about these and other issues but they've completely ignored the feedback.

For example:
https://www.virustotal.com/gui/file/325afd2f911b0156bc38708c91e7ac399c8a93b190f4124a6e72e030c166c1f2/details

* It says the binary is published by Microsoft when it's in fact published by TechPowerUp.
* The Imphash value seems to be invalid and doesn't match other tools.
* The 'First Seen In The Wild' value is showing 1 year earlier than the time it was in fact compiled.
* The tags include 'overlay' when the binary doesn't have any overlays.
* The tags also include 'invalid-signature' even though it has a valid signature.
* The tags also include 'invalid-rich-pe-linker-version' when it has valid richheader versions but VT doesn't parse it correctly.

So I've been considering removing support for VT because their service has become unreliable/inaccurate reporting incorrect information and they don't seem to care.

**Comment by Progress1** [comment]
I see... I compare it with Process Explorer and they have same problem (show same as you)
No, keep it.  VT is powerful feature. They fix it with the time ... Maybe you can additionally "steal" some functionality from PE and show ratio as hyperlink that open exact page with report ;-)

![image](https://user-images.githubusercontent.com/10151485/115364340-95de4a80-a1c3-11eb-8b87-8ba5b12926d6.png)

**Comment by dmex** [comment]
Related to #454
