### ISSUE TITLE
Tray icons dissappeared

### ISSUE THREAD

**Issue by kleuter** [processhacker/processhacker#884]
Old bug, happens with the latest version as well (3.0.4025), 

**To reproduce**
Place the following preferences file into the app directory:
[ProcessHacker.exe.settings.zip](https://github.com/processhacker/processhacker/files/6422068/ProcessHacker.exe.settings.zip)

If I delete the preferences file (go back to defaults), tray icons begin working normally.

**Comment by dmex** [comment]
It used to be that users complained that PH didn't remember their tray icon layout... So I added GUIDs required by the Windows shell to persist their tray icon settings and now the problem is that the shell remembers those settings too well.

If you execute processhacker.exe using two different paths the shell won't allow PH to show tray icons with those same GUIDs without resetting those GUIDs.

1) Exit Process Hacker.
2) Delete the `IconGuids` setting from the settings file.
3) Delete the `ProcessHacker.ExtendedTools.TrayIconGuids` setting from the settings file.
4) Relaunch Process Hacker.

New GUIDs will be created for the tray icons and they'll reappear on the system tray 👍

**Comment by kleuter** [comment]
Thanks for explaining the situation.

I acknowledge that this is a Pro tool, but it would be still nice to able to to that reset in the app, at least with a command line switch.

**Comment by dmex** [comment]
@kleuter 

You can do in the app using the advanced setting editor? Double-click the setting and delete the text:

![image](https://user-images.githubusercontent.com/1306177/117066366-fc3e9d80-ad6b-11eb-9075-b896d4b92e1e.png)
