### ISSUE TITLE
C1047 error while compiling 

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#908]
**Describe the bug**
While compiling, C1047 errors. Yesterday and today source 
![Снимок экрана (73)](https://user-images.githubusercontent.com/42459158/120144631-ed240180-c1ea-11eb-902c-e548e008760a.png)
![Снимок экрана (74)](https://user-images.githubusercontent.com/42459158/120144641-f57c3c80-c1ea-11eb-973c-727104e21581.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. Vista]

**Additional context**

**Comment by dmex** [comment]
Which version of Visual Studio are you using?

The problem is that your version isn't compatible with our pre-compiled static libraries. You have to recompile `\tools\thirdparty\thirdparty.sln` for both Release and Debug.

**Comment by Avtroman** [comment]
> Which version of Visual Studio are you using?
> 
> The problem is that your version isn't compatible with our pre-compiled static libraries. You have to recompile `\tools\thirdparty\thirdparty.sln` for both Release and Debug.

VS2019 16.10

Ok I try later

**Comment by Avtroman** [comment]
> Which version of Visual Studio are you using?
> 
> The problem is that your version isn't compatible with our pre-compiled static libraries. You have to recompile `\tools\thirdparty\thirdparty.sln` for both Release and Debug.

Builded OK

**Comment by dmex** [comment]
> VS2019 16.10

I have 16.10 and couldn't reproduce the build issues so not sure why yours failed but mine doesn't... Either way I'll update the precompiled libraries after Appveyor updates their build image 👍

**Comment by Biswa96** [comment]
Why are those precompiled?

**Comment by dmex** [comment]
> Why are those precompiled?

The same reasons anyone uses a precompiled library? 🤔

Thirdparty is completely isolated from the project which is necessary for licensing. It also contains static code that rarely if ever changes and a precompiled library significantly reduces compilation time required to build the project.

There are 5 solutions in that project with a significant amount of code that would otherwise have to be compiled by everyone, every single time you build the project including by Appveyor when they compile the nightly builds so having a precompiled library saves a significant amount of compilation time. This also majorly improves performance of various Visual Studio features because it doesn't have to index/compile databases for intellisense and search since all that code is completely isolated.

I don't know why it needs explaining since everyone does this (including the Windows SDK). I think the issue is that recent versions of Visual Studio changed those error messages and error C1047 stopped telling you thirdparty.lib caused the problem and instead only saying its phlib.lib 🤷‍♀️

**Comment by Biswa96** [comment]
I think ProcessHacker is not so huge project which can time out any CI builds.

**Comment by dmex** [comment]
> ProcessHacker is not so huge project which can time out any CI builds.

CI wasn't the problem.
