### ISSUE TITLE
Immunet/ClamAV reports Virus.Prochack

### ISSUE THREAD

**Issue by sebma** [processhacker/processhacker#915]
**Describe the bug**

**To Reproduce**
1. Download process hacker from https://sourceforge.net/projects/processhacker/files/processhacker2/processhacker-2.39-setup.exe
2. Install process hacker
3. [Immunet](https://www.immunet.com/) pops up a quarantine error detecting a `W32.ProcHack.22mg.1201`

**Expected behavior**
Immunet/ClamAV detects no arm and does nothing.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Windows 7SP1

**Comment by dmex** [comment]
I researched the ClanAV signature and wasn't able to find any information about why PH was added to the signature database except that it was added on September 13th, 2020 (25929) with the label:

`PUA.Win.Virus.Prochack-9757351-0`
https://lists.clamav.net/pipermail/clamav-virusdb/2020-September/007316.html

The ClamAV documentation for PUA says that these dual PUA/Virus labels are are invalid:
`The Virus/Ransomeware/Trojan/etc malware categories or subcategories for PUA signatures were mistakenly selected by automated tools. Those tools have since been fixed and no new signatures should appear with these names.`
https://www.clamav.net/documents/potentially-unwanted-applications-pua

The committer was `David Raynor` who according to their site:
`David Raynor is the core engine developer for ClamAV. He was a developer of a major scalable security system for the United States Department of Homeland Security before coming to Sourcefire.`

Sourcefire was bought by Cisco and that was the same company that hijacked our update/forum server last year. They also created and issued dozens of fraudulent SSL certificates for our domains and used their OpenDNS servers to redirect our update server/website traffic via MITM attack to their own server and we had to get Australian police involved: #556 

I've submitted a false positive report via the ClanAV website... we'll see what happens this time I guess.

**Comment by garoto** [comment]
Holy shit.

**Comment by sebma** [comment]
@dex Amazing info. 
I wonder still how this Immunet works, I thought it was using ClamAV as a backend so I tried running clamscan manually on my Ubuntu 20.04 LTS system : 
```bash
$ sudo freshclam
Fri Jun 11 15:28:43 2021 -> ClamAV update process started at Fri Jun 11 15:28:43 2021
Fri Jun 11 15:28:43 2021 -> daily.cld database is up-to-date (version: 26198, sigs: 3988566, f-level: 63, builder: raynman)
Fri Jun 11 15:28:43 2021 -> main.cvd database is up-to-date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Fri Jun 11 15:28:43 2021 -> bytecode.cld database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)
$ sha256sum processhacker-2.39-setup.exe 
28042dd4a92a0033b8f1d419b9e989c5b8e32d1d2d881f5c8251d58ce35b9063  processhacker-2.39-setup.exe
$ time clamscan processhacker-2.39-setup.exe 
/home/sebastien/win/softs/processhacker-2.39-setup.exe: OK

----------- SCAN SUMMARY -----------
Known viruses: 8538127
Engine version: 0.103.2
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 2.30 MB
Data read: 2.16 MB (ratio 1.06:1)
Time: 60.903 sec (1 m 0 s)
Start Date: 2021:06:11 15:26:23
End Date:   2021:06:11 15:27:24

real	1m0.918s
user	0m55.595s
sys	0m2.226s
$ 
```
It finds no malware. I don't understand.

**Comment by GameGeek126** [comment]
Hmm virustotal.com shows that many sites are blocking this tool.

It's unfortunate considering how useful it is.

**Comment by dmex** [comment]
> virustotal.com shows that many sites are blocking this tool

Also shows hundreds of comments from users complaining about those companies targeting PH... If anything it serves as a good example of industry corruption and incompetence. See #454

> I've submitted a false positive report via the ClanAV website

I still haven't received any response from them.

**Comment by dmex** [comment]
I still haven't received any response but then they've stopped blocking the application so I'll close this as related to #454

**Comment by sebma** [comment]
@dmex 

> I still haven't received any response but then they've stopped blocking the application so I'll close this as related to #454

Who do you mean by `they've stopped blocking the application` : ClamAV or Windows ?

**Comment by dmex** [comment]
ClamAV

**Comment by sebma** [comment]
@dmex Cool. 
I only was able to find [this](https://lists.clamav.net/mailman/search?query=Prochack&submit=Search%21&idxname=clamav-virusdb&max=20&result=normal&sort=score)

Do you more info. about ClamAV having stopped blocking processhacker ?

**Comment by dmex** [comment]
> Do you more info. about ClamAV having stopped blocking processhacker ?

I just assumed they unblocked it because I couldn't find the signatures... I've re-opened the ticket.

**Comment by BlueScreenBuddy** [comment]
Symantec Endpoint Protection does NOT like this product. Flags it as: Hacktool.ProcHack!g1

SEP 14.3.1148.0100

**Comment by dmex** [comment]
> I've re-opened the ticket.

6 months later and they still haven't responded... 

> Symantec Endpoint Protection does NOT like this product

Your their customer, you sort them out...

**Comment by BlueScreenBuddy** [comment]
It's your software, dude.

**Comment by mrsshr** [comment]
> It's your software, dude.

He has no responsibility. THE SOFTWARE IS PROVIDED AS IS WITHOUT WARRANTY.

Do not use PH if you do not agree.

**Comment by Masamune3210** [comment]
It's not a virus, Symantec just has really sucky heuristics and apparently doesn't respond to false reports

**Comment by BlueScreenBuddy** [comment]
I'm fully aware it's not a virus. I never asked if it was.

**Comment by dmex** [comment]
> He has no responsibility. 

It's only when it comes to stuff like technical support that there isn't a guarantee but we do absolutely have responsibilities. For example:

1) This product contains no spyware.
2) This product contains no malware.
3) This product contains no cheating.
4) This product contains no security issues.

I can or anyone can guarantee those statements are correct and true because this is an open source project where everything can be reviewed and criticized. 

This project has been around since 2008 and has more than 15 million downloads. If it contained malicious code then someone would have posted this somewhere alerting others about the problem.

Open source means anyone can report or discuss issues so they can be addressed just like the Linux kernel or other large projects. Vendors withholding information and refusing to communicate does not help anyone. If they've found a security issue, refusing to talk with developers guarantees: 

A) The issue won't get fixed.
B) The attacks will continue.
C) The attacks will cause more damage and more victims (since vendors prevented the issue getting fixed by keeping secrets). 
D) They've chosen to side with the attackers and let them continue rather than siding with open source projects.

D is my personal opinion... If vendors found an issue with this project, not sharing those issues with the development team prevents anyone fixing those issues... they're preferring to support the attackers by keeping these exploits and attacks secret from the developers, so the attacks will continue instead of getting fixed.

> Symantec doesn't respond to false reports

If they wanted us to fix the issue then they would respond but they don't want anyone to change anything... The ugly truth is vendors want these attacks to continue because more attacks serve to drive more sales of their AV software since it's the only thing that would stop the attack... letting developers fix their code would also stop the attack but then AV software has no reason to exist because the attacks won't exist.

> It's your software, dude.

We opened a support ticket and emailed them in July (6 months ago) but they haven't replied... They're not letting us talk with them, so we don't have any easy options to resolve the problem... If you use their software then whitelist the application, submit a complaint to them (mentioning the above problems).

Even better just switch to a vendor like CrowdStrike or Malwarebytes since both of these vendors actively support open source projects and have worked on issues with us in the past which no other vendor has done.

**Comment by BlueScreenBuddy** [comment]
I wasn't aware they basically ghosted you. Apologies. I do appreciate the answer.
