### ISSUE TITLE
Add option to only upload unverified images to VirusTotal

### ISSUE THREAD

**Issue by hoffr** [processhacker/processhacker#917]
**Is your feature request related to a problem? Please describe.**
I appreciate conservation of resources, whether of the internet or of the local system. Maybe this could help reduce the load on VT's servers, since they do seem to have issues a lot

**Describe the solution you'd like**
Add an option in the settings xml to only upload unverified images to VirusTotal, or have this as the default

**Describe alternatives you've considered**

**Additional context**
Definitely a minor request, only considerable if it doesn't take too much work to implement.

**Comment by yfdyh000** [comment]
Unverified images meaning digital signature? Some malware has a legal digital signature that is stolen.
If you say that only checks the files that has not been scanned, I think the program will not upload each complete executable, and I didn't see the automatic upload option.

**Comment by dmex** [comment]
> only upload unverified images to VirusTotal

There isn't any reliable method for determining what's unverified since malware/spyware uses stolen certificates and/or patches functions like WinVerifyTrust used to verify signatures.

> only checks the files that has not been scanned

VirusTotal caches results indefinitely unless you force a rescan. Even when the file was already scanned those results can be years out of date. I've seen this even with older PH binaries from years ago with their last scan date from ~ 2018 showing as malicious/PUA until you click rescan/refresh the results and they would show clean.

So if we only upload non-existent files we would end up showing out of date information for files that do exist.

> Maybe this could help reduce the load on VT's servers, since they do seem to have issues a lot

People are DDoSing their infrastructure by initiating rescans for more than 700,000 binaries every second. The last attack used the Sysinternals VT apikey for initiating a rescan of > 6 million binaries effectivly shutting down their services.... So they've started clamping down with hard limits and hard restrictions to keep the service online - there isn't much that we can do since that DDoS abuse prevents everything from working. 

> I didn't see the automatic upload option.

Automatic upload is not available or included with PH because that's an information disclosure attack. 

This was especially a problem years ago when I worked at Electronic Arts because tools like Process Explorer automatically upload unknown binaries and leaked the development of internal binaries and unreleased games - In some cases researchers found these binaries for those games - years in advance of any public announcements - reported them to the media and the stock market whom pilfered the information for profit because they were able to follow the development and reverse engineer those binaries for games knowing when they were almost ready for release and buy stocks before these games were announced. 

I reported a similar problem to Microsoft recently as hundreds of their internal-use-only tools leaked on VirusTotal including binaries for security patches under developement - you could see exactly what Microsoft were developing internally, unrelelased security patches/DLLs and changes they were testing months in advance all because tools like Process Explorer were automatically uploading unknown binaries.... So automatic uploads to VT won't ever be included with Process Hacker due to the information disclosure security issues with such feature.
