### ISSUE TITLE
Show CPU architecture (x64, ARM64) and not only Bits (64)

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#955]
Processhacker shows Image 64Bit but you can't know if x64 or ARM64. Taskmanager now has a column for this:

![image](https://user-images.githubusercontent.com/8274816/130323110-198b96d7-e0e1-4045-a3ca-0f37084c0cef.png)

_Originally posted by @MagicAndre1981 in https://github.com/processhacker/processhacker/issues/71#issuecomment-903115117_

**Comment by dmex** [comment]
64-bit is correct for both of those processes since ARM64 and x64 are both using 64-bit pointers. 

The new architecture column added to taskmgr is using a new infoclass specific to Windows 11 named `SystemSupportedProcessorArchitectures2` which is newer than the existing `SystemSupportedProcessorArchitectures` class on Win10 so it'll probably have to wait until win11 releases.

**Comment by Biswa96** [comment]
How about using `GetProcessInformation(ProcessMachineTypeInfo)` and check the return value? My findings are here https://github.com/msys2/MINGW-packages/discussions/8991

**Comment by MagicAndre1981** [comment]
> 64-bit is correct for both of those processes since ARM64 and x64 are both using 64-bit pointers.

yes, I know this, this is why want a way to see if the process is x64 or ARM64.

**Comment by dmex** [comment]
> yes, I know this, this is why want a way to see if the process is x64 or ARM64.

I'm aware. Just pointing out a difference in the two sets of data as one is bitness and the other is architecture and PH only currently shows the bitness.
