### ISSUE TITLE
CPU usage between Taskmgr and ProcessHacker differs when "Enable cycle-based CPU usage" is enabled on Win11 ARM64

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#970]
**Describe the bug**

Run Taskmgr (ARM64) and ProcessHacker (x64) on Windows 11 ARM64 and the overall CPU usage differs.

**To Reproduce**
1.  Run Taskmgr (ARM64), go to Perf->CPU
2.  Run ProcessHacker (x64)->View Systeminformation->CPU 
3.  compare CPU usage graph and PH reports 99% usage while TM shows less CPU usage. 

**Expected behavior**

both tools show nearly the same values as they do for the individual cpu usage of the cores, here the values look the same for both. 

**Screenshots**

![image](https://user-images.githubusercontent.com/8274816/131220377-0ef32678-a27d-4f8b-9a39-ec2f9dac7412.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 11 ARM64 22000.168

**Additional context**

Win11 ARM64 runs on Raspi 4 via USB to SATA Adapter on a SATA SSD.

**Comment by ge0rdi** [comment]
Try to disable the `Enable cycle-based CPU usage` setting.
I think there was some issue with it when I was playing with ARM64 PH on Surface Pro X some time ago.

**Comment by MagicAndre1981** [comment]
> Try to disable the `Enable cycle-based CPU usage` setting.

great, that's it. turning it off fixes it. Now both look similar.

**Comment by ge0rdi** [comment]
I was trying to figure out what's wrong with cycle-based usage on ARM64 back then, but I really have no clue :(
Hopefully someone else will be able to help with this.

@dmex 
Maybe for now `Enable cycle-based CPU usage` should be disabled on ARM64 by default?

> I changed the title and leave it open for tracking, maybe this can be improved.

Eventually add ARM64 to the title (?). As far as I know the option works well on non-ARM64.

**Comment by MagicAndre1981** [comment]
> I was trying to figure out what's wrong with cycle-based usage on ARM64 back then, but I really have no clue :(

have you compiled PH for ARM64 or used official x86/x64 nightly version? 

> Eventually add ARM64 to the title (?). As far as I know the option works well on non-ARM64.

done

**Comment by dmex** [comment]
> compare CPU usage graph and PH reports 99% usage while TM shows less CPU usage.

Task Manager will consistently show lower utilization because Microsoft changed taskmgr to instead use the "Processor Utility" performance counter which is a garbage statistic that does not report the correct utilization.

1) It'll consistently report values 10-20% higher than the real value when the utilization is above 50%
1) It'll consistently report values 10-20% lower than the real value when the utilization is below 50%

For example:
![image](https://user-images.githubusercontent.com/1306177/131223317-95c2124d-4bba-4004-82d6-f2524981dd3c.png)

This change was documented here:
https://docs.microsoft.com/en-US/troubleshoot/windows-client/performance/cpu-usage-exceeds-100

That document attempts to justify the change but the reality is that the statistic is broken and taskmgr now consistently reports inaccurate utilization. You might also notice the uptime reported by taskmgr is incorrect because they forgot to include the bias.

> Run Taskmgr (ARM64) and ProcessHacker (x64) on Windows 11 ARM64 and the overall CPU usage differs.

What does Process Explorer show? If PE is the same as PH then we're both correct and taskmgr is wrong.

**Comment by MagicAndre1981** [comment]
> 
> What does **Process Explorer** show? If PE is the same as PH then we're both correct and taskmgr is wrong.

Process Explorer also shows lower values:

![image](https://user-images.githubusercontent.com/8274816/131224674-d07d82d2-d360-4b8a-90bf-75f2fa5a8a5d.png)

**Comment by MagicAndre1981** [comment]
capturing cpu usage with `wpr -start CPU` also shows low usage ( I see some periodically spikes from taskmgr from the graph redraws and this is expensive on the Pi as it uses software rendering without WDDM drivers).

So all 3 tools probably show individual core usage correctly in the sysinfo graphs, but PH has higher value in summary view when cycle-based CPU usage is used on ARM64. 

@ge0rdi what are your values on the Surface Pro X?

**Comment by ge0rdi** [comment]
@MagicAndre1981 
>have you compiled PH for ARM64 or used official x86/x64 nightly version?

I have used native ARM64 PH.

> what are your values on the Surface Pro X?

I don't have Surface Pro X at hand at the moment, so can't check.
We have some at work, so I can eventually borrow one and have a look.

But with `Enable cycle-based CPU usage` option enabled it showed quite weird numbers. That's why I've disabled it.

I was thinking it is related to big.LITTLE ARM architecture as Surface Pro X uses CPU that has 4 powerful cores and 4 efficient cores (running at different clock frequency).
Maybe I'll try to debug it once again.

**Comment by ge0rdi** [comment]
@dmex 
> That document attempts to justify the change but the reality is that the statistic is broken and taskmgr now consistently reports inaccurate utilization.

They are simply showing different metric. The document explains it well. I'd not call it broken.
Probably it would be better if TM called it _Utility_ instead of _Utilization_ to avoid confusion.

Personally I'd stick to the good old utilization metric (as that makes more sense to me), so appreciate that PH does it that way.
But if MS decided to show something else that's their choice.

**Comment by MagicAndre1981** [comment]
> I was thinking it is related to big.LITTLE ARM architecture as Surface Pro X uses CPU that has 4 powerful cores and 4 efficient cores (running at different clock frequency).

the Pi4 only has 4 Cortex-A72 cores, no big.LITTLE

**Comment by dmex** [comment]
@MagicAndre1981 

Why is your latency so high or is this a separate issue?

![image](https://user-images.githubusercontent.com/1306177/131230388-fb8879e2-fef9-4a1d-899c-81339d5a21ff.png)

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981
> 
> Why is your latency so high or is this a separate issue?

I have no idea. Could be a Raspi thing

**Comment by MagicAndre1981** [comment]
This also happens because of running x64 version and [skips your check](https://github.com/processhacker/processhacker/blob/caf9d83ab6193e55970246e54e58af0556ffd903/ProcessHacker/syssccpu.c#L1053)

@dmex

**Comment by dmex** [comment]
> running x64 version and skips your check

What did you expect to happen? You're compiling the 64bit build and running it emulated so the x64 code will execute. Why should native users be saddled with runtime checks to detect ARM emulation? If you want the appropriate checks for ARM then compile the native ARM version. 

> They are simply showing different metric

It's more than that. They wouldn't use those values if they cared at all about accuracy and reliability. They've done it this way to deliberately mislead people into thinking utilization is lower on Win10 and Win11 compared to previous versions because nobody realizes they've changed the goal posts/game and are still calling it the same thing as before.

You can see for yourself with benchmarking tools (like my screenshot above) their values are +/- 20% the actual utilization. A program using 20% of the processor is only shown by Task Manager to have 5% utilization while programs utilizing 50% are showing 65%.

**Comment by ge0rdi** [comment]
> They've done it this way to deliberately mislead people into thinking utilization is lower on Win10 and Win11 compared to previous versions because nobody realizes they've changed the goal posts/game and are still calling it the same thing as before.

C'mon. There is no need to see evil behind each change MS is doing.
They simply wanted to accommodate for modern CPU's that don't run on nominal frequency all the time.

Here is good article that explains what is going on exactly:
https://aaron-margosis.medium.com/task-managers-cpu-numbers-are-all-but-meaningless-2d165b421e43

And it actually explains why its not good way of showing things (especially the capping to 100% that makes those numbers totally  useless).
But that's really not about some malicious intent.
MS decided to _improve_ something, but ultimately failed at that (as with many other things).

Anyways, I think this is not related to the issue with cycle-based CPU usage on ARM64.
Have a look at @MagicAndre1981's screenshot. PH shows 99% CPU usage even if CPU is used very lightly.

Also when I was playing with ARM64 device I noticed that PH showed really weird CPU usage values.
Unless I disabled cycle-based CPU usage option. After that it showed much more meaningful (expected) numbers.

**Comment by ge0rdi** [comment]
FYI, this is screenshot from idle Surface Pro X (ARM64 PH compiled from master) when cycle-based CPU usage is enabled:
![image](https://user-images.githubusercontent.com/2453094/131249686-1c1d6d82-1c2f-413e-ba8d-3bb2f90e474c.png)

The machine does basically nothing yet PH shows quite high CPU usage.
When cycle-based CPU usage is disabled it goes back to normal:
![image](https://user-images.githubusercontent.com/2453094/131249726-e1b3e011-5ce0-4818-829b-7fbe5120535a.png)

**Comment by dmex** [comment]
> There is no need to see evil behind each change MS is doing.

They knew exactly what they were doing. I didn't just wake up and decide their utilization change was evil because of this one thing.. These same people have made a long list of things in the last decade that they knew was really bad and still went along with it but this was one of the most obvious.

> I was playing with ARM64 device I noticed that PH showed really weird CPU usage values

Microsoft likely changed the APIs again just to fuck us over and that's not the first time. They regularly change the APIs and conceal the typedefs and structures just to fuck us over... All the calls and types are obfuscated and have to be reverse engineered. I don't have ARM hardware, so I have literally no idea what they've done here or why.

You want me to figure out why PH shows inaccurate statistics on ARM? I have to reverse engineer Windows, I have to reverse engineer the hardware - I have neither the hardware to reverse, or the tools for reverse engineering Windows on ARM.

Microsoft literally never publish or document a single thing about their APIs for preforming utilization calculations - The typedefs that we have reverse engineered are regularly changed just to fuck over third parties competing with Task Manager... everything has to be reverse engineered, all the fucking time.

Microsoft obviously changed something on ARM but without the hardware and without the tools to RE their software and without Microsoft sharing the typedefs... I literally have no idea what Windows on ARM is doing or how they're doing it or why PH is showing incorrect statistics.

> PH shows 99% CPU usage even if CPU is used very lightly.

What did you expect to happen here? What do you want me to do?

**Comment by ge0rdi** [comment]
> You want me to figure out why PH shows inaccurate statistics on ARM? I have to reverse engineer Windows, I have to reverse engineer the hardware - I have neither the hardware to reverse, or the tools for reverse engineering Windows on ARM.

Never said anything like that.

What I suggested though is to simply disable cycle-based CPU usage option on ARM64 by default.
As it seems to not work correctly.
I can eventually try to submit PR with said change if you are ok with it.

Also I may try to debug it once more (I have access to ARM64 hardware). Will try to share some findings.

**Comment by ge0rdi** [comment]
I have noticed something interesting on Surface Pro X.

Here is screenshot of `Idle` process threads when system is completely idle (TM shows ~2-3%):
![image](https://user-images.githubusercontent.com/2453094/131263819-81b8d0bf-88d9-466e-8884-aced09f2a89f.png)

Note the `Cycles delta` column. The numbers are very small.

On my desktop machine (Ryzen 5600X with base frequency 3.7GHz) those numbers are high, like 3'600'000'000-3'700'000'000 which corresponds to number of cycles of 3.7GHz CPU in one second (default update interval in PH).

Surface Pro X has CPU with 4 cores running at 3GHz and 4 cores running at 1.8GHz.
So I'd expect those idle cycle numbers to be in order of billions (not millions).

If I run something that will fully use one CPU core I can see `Cycles delta` at numbers around 2.9bln which would correspond to 3GHz CPU.

So it seems that CPU cycles are correctly reported for standard processes, but incorrectly for idle process.
And since number of cycles for idle process is way smaller that it is supposed to be, in the end it looks like processes use much bigger portion of CPU that they really use.

**Comment by MagicAndre1981** [comment]
thanks for the pictures, so it is not just me with my unsupported Raspi4 but also for a Microsoft product.

**Comment by ge0rdi** [comment]
I have found this [article](https://community.arm.com/developer/ip-products/processors/f/cortex-a-forum/7019/arm-v8-pmu-cycle-counter) where author observed similar issue with `PMCCNTR_EL0` counter on ARM.
This counter seems to be _equivalent_ of `RDTSC` on x86.

One of answers states that this counter is not always incremented, for example in situations where CPU core is idle or waiting for some event (to conserve energy). Also it counts at different pace when core runs at reduced clock.

It seems that MS is also using this counter.
I have looked at `KeQueryTotalCycleTimeThread` that seems to update thread's cycle time and it uses `ARM64_SYSREG(3, 3, 9, 13, 0)` (which should be `PMCCNTR_EL0`).
x64 kernel uses `RDTSC` at that place.

It may happen that cycle-based CPU usage really won't work currently on ARM.
At least until MS starts to use different counter that will increase always at the same pace (if that's even possible).

So I think I will prepare PR that will disable cycle-based CPU usage on ARM by default (eventually completely removing/ignoring that option if it is desired).

BTW I was wondering why cycle-based CPU usage does even work on modern CPUs that are often changing frequency (either to lower consumption on idle or boost performance when busy). Because if true CPU cycles were counted then some will have bigger weight that the others (e.g. when CPU core is running at higher frequency it will count more cycles in given time frame).

Fortunately `RDTSC` increments at constant rate on modern x86 CPUs (no matter of actual CPU core clock).
This is from Intel manual:
> the time-stamp counter increments at a constant rate. That rate may be set by the 
maximum core-clock to bus-clock ratio of the processor or may be set by the maximum resolved frequency at 
which the processor is booted

**Comment by dmex** [comment]
> I have looked at KeQueryTotalCycleTimeThread that seems to update thread's cycle time and it uses ARM64_SYSREG(3, 3, 9, 13, 0) (which should be PMCCNTR_EL0).
x64 kernel uses RDTSC at that place.


This is related to the ReadTimeStampCounter macro in the Windows SDK used by the kernel and third parties... For whatever reason it uses the wrong types and instructions for ARM basically calling rdtsc for everything.

The ifdef for ARM64 especially seems to be using the wrong value with PMCCNTR instead of CNTVCT?

I've been testing a replacement using the correct definitions but this won't fix the SDK or the Windows kernel:
![image](https://user-images.githubusercontent.com/1306177/131570576-b3813b14-5ffe-46da-a004-8389b4d738d5.png)

> MS starts to use different counter

I did ask last year and never heard back so I doubt they'll ever change it. Windows ARM counters will probably remain broken for more than a decade.

> I think I will prepare PR that will disable cycle-based CPU usage on ARM by default

Why should we be forced to disable cycle counters because of a Microsoft screwup? I'd prefer we keep them enabled just to demonstrate how broken ARM is because of Microsoft and so they'll fix the problem rather than ignore it.

**Comment by ge0rdi** [comment]
> Why should we be forced to disable cycle counters because of a Microsoft screwup? 

I thought Process Hacker is here to help people with observing what goes on on their system.
Showing wrong CPU usage doesn't help with that.

Seriously, what's the problem to avoid using some feature if we know it doesn't work?

> I'd prefer we keep them enabled just to demonstrate how broken ARM is because of Microsoft and so they'll fix the problem rather than ignore it.

Have you ever considered that it may be not broken?
That `CycleTime` could mean real number of cycles spent on CPU?

This is from [QueryThreadCycleTime](https://docs.microsoft.com/en-us/windows/win32/api/realtimeapiset/nf-realtimeapiset-querythreadcycletime) documentation:

> The number of CPU clock cycles used by the thread. This value includes cycles spent in both user mode and kernel mode.

That sounds like number of cycles really spent on CPU by given thread (no matter what frequency of those cycles was).

> Do not attempt to convert the CPU clock cycles returned by QueryThreadCycleTime to elapsed time. This function uses timer services provided by the CPU, which can vary in implementation. For example, some CPUs will vary the frequency of the timer when changing the frequency at which the CPU runs and others will leave it at a fixed rate. The behavior of each CPU is described in the documentation provided by the CPU vendor.

This clearly states that cycle counting may not run at constant pace on some platforms (exactly as we have observed on ARM64).
And this is official documentation (means it presents the intent behind CPU cycles reported by Windows).

To me it looks like cycle-based CPU usage works just by _accident_, because for modern x86 CPUs Windows uses cycle counters that actually are not related to CPU cycles at all.

**Comment by dmex** [comment]
> I thought Process Hacker is here to help people with observing what goes on on their system.

It is but Microsoft are making this impossible by deliberately fucking us over in their Task Manager wars.

> This clearly states that cycle counting may not run at constant pace on some platforms (exactly as we have observed on ARM64).
And this is official documentation (means it presents the intent behind CPU cycles reported by Windows).

We don't use these counters for elapsed time so this isn't an issue.

> Seriously, what's the problem to avoid using some feature if we know it doesn't work?

Why does the Windows API return garbage for KernelTime, UserTime and IdleTime for each processor? Did Microsoft deliberately screw those counters on ARM just to make competitors software unreliable or is there some reason why Windows doesn't properly increment those values?

**Comment by ge0rdi** [comment]
> We don't use these counters for elapsed time so this isn't an issue.

You expect those counters to be increased at fixed frequency. So that you can compute CPU utilization.
Indirectly you are using them for counting elapsed time (cycle count at fixed known frequency ~ time elapsed).

The documentation says that it just may not work that way on all platforms.

> Why does the Windows API return garbage for KernelTime, UserTime and IdleTime for each processor?

Hmm. I don't think there is a problem with reported _times_.
The "problem" is with reported _cycles_ (not the same thing).

> The screenshot above shows the per-core utilization works but the totals make no sense so there's something dodgy

That's because per-core utilization is computed using _times_ not _cycles_.
It is computed using `PhCpus*Delta` arrays (kernel, user, idle) that are filled with times reported by `NtQuerySystemInformation(SystemProcessorPerformanceInformation)` (inside `PhpUpdateCpuInformation` function).

Whole CPU (and per-process) utilization is computed using number of _cycles_ spent in actual computing and number of _cycles_ spent in idle. Since these two counters don't run on the same frequency (for example idle cores run at smaller frequency or are disabled completely) it is obvious that resulting numbers will be wrong.

There is nothing dodgy going on.

Windows on ARM seems to count real CPU cycles, instead of using some counter that runs on fixed frequency no matter what CPU cores are doing.
Thus using cycle-based CPU usage doesn't make any sense on this platform.
